// ─── JesAI Company Law Knowledge Module ──────────────────────
// NLC validated — Nazmul, Advocate, Supreme Court of Bangladesh
// CURRENT LAWS ONLY:
// ✅ Companies Act 1994 (current, with all amendments)
// ✅ Partnership Act 1932
// ✅ RJSC Online System 2024 (roc.gov.bd)
// ✅ One Person Company Rules 2020
// ✅ Foreign Company Registration Rules 2018
// ✅ BIDA Act 2016 + Investment Policy 2021
// ✅ Bangladesh Securities and Exchange Commission Rules
// ✅ Societies Registration Act 1860 (for NPO)
// Last verified: 2025-03-09

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "co-pvt-001",
    area: "company",
    jurisdiction: "BD",
    title: "Private Limited Company — Companies Act 1994",
    rule: "Minimum 2, maximum 50 shareholders. Minimum 2 directors. Shares cannot be offered to public. Name must include 'Limited' or 'Ltd'. Registered with RJSC. Separate legal entity with limited liability.",
    source: "Companies Act 1994, Sections 2, 9, 11",
    certainty: "confirmed",
    tags: ["private limited", "pvt ltd", "company", "shareholders", "directors", "limited liability"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-opc-001",
    area: "company",
    jurisdiction: "BD",
    title: "One Person Company (OPC) — Rules 2020",
    rule: "Single Bangladeshi individual can incorporate OPC. Sole member is sole director. No share transfer or new members without converting. Limited liability applies. Cannot be used for banking business.",
    source: "Companies Act 1994 (amended); One Person Company Rules 2020",
    certainty: "confirmed",
    tags: ["opc", "one person company", "single director", "sole shareholder"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-partnership-001",
    area: "company",
    jurisdiction: "BD",
    title: "Partnership — Partnership Act 1932",
    rule: "Partnership registration with RJSC is optional but recommended. Unregistered firm cannot sue. Maximum 20 partners (10 in banking). Partners have unlimited personal liability.",
    source: "Partnership Act 1932, Sections 4, 69",
    certainty: "confirmed",
    tags: ["partnership", "firm", "partners", "unlimited liability", "partnership deed"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-foreign-001",
    area: "company",
    jurisdiction: "BD",
    title: "Foreign Company Registration",
    rule: "Foreign companies must register with RJSC within 30 days of establishing Bangladesh presence. Options: Branch Office (full commerce), Liaison Office (promotion only), Subsidiary (new BD company). BIDA registration also required.",
    source: "Companies Act 1994, Sections 379-386; Foreign Company Rules 2018",
    certainty: "confirmed",
    tags: ["foreign company", "branch office", "liaison office", "bida", "fc"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-annual-001",
    area: "company",
    jurisdiction: "BD",
    title: "Annual Compliance — Companies Act 1994",
    rule: "AGM within 120 days of financial year end. Annual return filed with RJSC within 21 days of AGM. Audited financials required. Non-filing: penalty + possible strike-off.",
    source: "Companies Act 1994, Sections 81, 192",
    certainty: "confirmed",
    tags: ["annual return", "agm", "audit", "rjsc filing", "compliance"],
    lastVerified: "2025-03-09",
  },
];

const qaBank: QAEntry[] = [
  // ════════ COMPANY FORMATION ════════
  {
    id: "co-qa-001",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["register company", "form company", "incorporate", "কোম্পানি গঠন", "কোম্পানি নিবন্ধন", "start company"],
    question: "How do I register a private limited company in Bangladesh?",
    irac: {
      issue: "Step-by-step process for incorporating a private limited company with RJSC?",
      rule: "Companies Act 1994 + RJSC Online System (roc.gov.bd): Name clearance → prepare MOA/AOA → online submission → payment → Certificate of Incorporation. Fully online since 2020.",
      application: "Minimum: 2 shareholders, 2 directors (same persons allowed), registered office in Bangladesh. All TINs required. Physical appearance at RJSC not required.",
      conclusion: "**Private Ltd Company Registration:**\n\n1. **Name clearance** — roc.gov.bd → 1-3 days\n2. **Prepare MOA & AOA** — define business, shares\n3. **Online application** — Form I, VI, XII\n4. **Pay RJSC fees** — based on authorized capital\n5. **Certificate of Incorporation** — 7-15 working days\n\n**Minimum requirements:**\n• 2 shareholders, 2 directors\n• TIN for all directors/shareholders\n• NID for Bangladeshi nationals\n• Registered Bangladesh office address\n\n**Total time:** 15-20 working days\n\n📋 Document list — ৳299\n📄 Full RJSC guide — ৳2,999\n📄 MOA + AOA drafting — ৳4,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-002",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company name clearance", "name approval rjsc", "কোম্পানির নাম ছাড়পত্র", "name availability company", "rjsc name check"],
    question: "How do I get company name clearance from RJSC?",
    irac: {
      issue: "Process for obtaining company name clearance?",
      rule: "Companies Act 1994, Section 11 + RJSC Rules: Name clearance required before incorporation. Apply online with 3 name options. Clearance valid 90 days. Cannot use: Bank, Insurance, Government, National without permission.",
      application: "roc.gov.bd → Apply name clearance → Submit 3 options → RJSC checks existing names → Approval/rejection in 1-3 working days.",
      conclusion: "**Name clearance:**\n1. roc.gov.bd → Name clearance application\n2. Submit 3 names in preference order\n3. Fee: ~BDT 200\n4. Result: 1-3 working days\n5. **Valid for 90 days** — register within this period\n\n**Prohibited:**\n• Identical to existing company\n• Deceptively similar names\n• 'Bank', 'Insurance', 'National', 'Government' without permission\n\n📋 Name clearance guide — ৳99",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-003",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["one person company", "opc", "single person company", "একক ব্যক্তি কোম্পানি", "single member company"],
    question: "Can one person form a company alone?",
    irac: {
      issue: "Can a single individual incorporate a company in Bangladesh?",
      rule: "One Person Company Rules 2020: Single Bangladeshi resident individual can form OPC. Limited liability applies. Cannot be incorporated by another company. Must name a nominee director.",
      application: "Solo entrepreneur wanting limited liability without a second partner → OPC is ideal. Owner's personal assets protected from company debts.",
      conclusion: "**OPC — One Person Company:**\n\n✅ **Requirements:**\n• Single Bangladeshi individual\n• Must be resident in Bangladesh\n• Cannot be another company\n• Name a nominee director (in case of death/incapacity)\n\n✅ **Benefits:** Limited liability, separate legal entity\n\n❌ **Restrictions:**\n• Cannot add new shareholders\n• Cannot issue shares to public\n• Cannot do banking business\n• Must convert to Pvt Ltd if member added\n\n📋 OPC registration guide — ৳299\n📄 Full OPC setup — ৳2,999",
    },
    escalate: false,
    relatedRules: ["co-opc-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-004",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company vs partnership", "pvt ltd vs firm", "কোম্পানি বনাম অংশীদারিত্ব", "which is better company or firm", "difference company firm"],
    question: "What is the difference between a company and a partnership firm?",
    irac: {
      issue: "How does a private limited company differ from a registered partnership?",
      rule: "Companies Act 1994 vs Partnership Act 1932: Key difference is legal status and liability. Company = separate legal entity with limited liability. Partnership = not separate, partners personally liable.",
      application: "Company can own property, sue, be sued in its own name. Partners are personally liable for firm debts — their personal assets at risk.",
      conclusion: "**Company vs Partnership:**\n\n| Feature | Pvt Ltd | Partnership |\n|---|---|---|\n| Legal entity | Separate ✅ | Not separate ❌ |\n| Liability | Limited ✅ | Unlimited ❌ |\n| Min members | 2 | 2 |\n| Max members | 50 | 20 |\n| Registration | Mandatory | Optional |\n| Tax rate | 27.5% | Slab rates |\n| Continuity | Perpetual | Can dissolve |\n\n**Use company:** Investment risk, limited liability needed.\n**Use firm:** Simple business, low compliance cost.\n\n📄 Business structure guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001", "co-partnership-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-005",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["register partnership", "firm registration", "অংশীদারিত্ব নিবন্ধন", "partnership deed registration", "register firm"],
    question: "How do I register a partnership firm?",
    irac: {
      issue: "Process for registering a partnership with RJSC?",
      rule: "Partnership Act 1932 + RJSC: Optional but strongly recommended — unregistered firm cannot file lawsuit. Apply at RJSC with partnership deed, Form I, NIDs of partners, TIN.",
      application: "Without registration, firm cannot sue third parties or partners in court. Registration cost is minimal — always worth registering.",
      conclusion: "**Partnership registration — RJSC:**\n\n**Documents:**\n• Partnership deed (signed by all partners)\n• Form I (application)\n• NID of all partners\n• Firm TIN + trade licence\n• Passport photos\n\n**Process:**\n1. Prepare + sign partnership deed\n2. Apply at RJSC (online or physical)\n3. Pay fee\n4. Certificate issued in 7-10 days\n\n**Without registration:** Cannot sue in court.\n\n📋 Partnership docs — ৳199\n📄 Partnership deed drafting — ৳2,999",
    },
    escalate: false,
    relatedRules: ["co-partnership-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-006",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["foreign company register", "branch office bangladesh", "liaison office", "বিদেশি কোম্পানি", "foreign branch bd"],
    question: "How does a foreign company register in Bangladesh?",
    irac: {
      issue: "How can a foreign company establish legal presence in Bangladesh?",
      rule: "Companies Act 1994, S.379-386 + Foreign Company Rules 2018: Must register with RJSC within 30 days of establishing Bangladesh presence. Branch Office: full commerce. Liaison Office: promotion only. Subsidiary: new BD company with foreign ownership.",
      application: "UK company opening Dhaka office to sell products → Branch Office (RJSC + BIDA). Foreign company setting up marketing coordination only → Liaison Office. Most flexible: Subsidiary (new BD Pvt Ltd with foreign shareholder).",
      conclusion: "**Foreign company options:**\n\n**Branch Office:**\n• Full commercial activity\n• Register: RJSC + BIDA\n• Tax: 37.5-40%\n\n**Liaison Office:**\n• Promotion/coordination only\n• No revenue allowed\n• Register: RJSC + BIDA\n\n**Subsidiary (Pvt Ltd):**\n• Most flexible\n• Standard 27.5% tax\n• Foreign shareholder up to 100% in most sectors\n\n📋 Foreign company docs — ৳399\n📄 Full guide — ৳4,999",
    },
    escalate: true,
    escalateReason: "Foreign company registration needs RJSC + BIDA + Bangladesh Bank coordination. WhatsApp NLC.",
    relatedRules: ["co-foreign-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-007",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["add director", "change director", "remove director", "পরিচালক পরিবর্তন", "director appointment removal"],
    question: "How do I add or remove a director?",
    irac: {
      issue: "Process for appointing or removing a director?",
      rule: "Companies Act 1994, S.92-107: Director appointment by shareholders at general meeting. File Form XII with RJSC within 28 days of change. Removal: ordinary resolution with special notice to director.",
      application: "Add director: Board meeting → EGM approval if required → Form XII at RJSC within 28 days → Register updated. Late filing attracts penalty.",
      conclusion: "**Director change — process:**\n\n1. Board meeting — resolution\n2. EGM if shareholders' approval needed\n3. File **Form XII** at RJSC within **28 days**\n4. Pay filing fee\n\n**New director documents:**\n• NID/Passport\n• TIN\n• Consent form (Form XII)\n• Photograph\n\n**Late filing:** BDT 1,000 + daily penalty\n\n📋 Director change docs — ৳199\n📄 Corporate change guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-008",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["change company address", "registered office change", "ঠিকানা পরিবর্তন", "rjsc address", "company address update"],
    question: "How do I change my company's registered address?",
    irac: {
      issue: "Process for changing registered office address with RJSC?",
      rule: "Companies Act 1994, S.77: Same district: board resolution + Form VI within 30 days. Different district: special resolution (75% shareholders) + EGM + RJSC approval.",
      application: "Moving within Dhaka: Board resolution + Form VI + new utility bill → RJSC updates records. Moving Dhaka to Chattogram: more complex EGM + newspaper advertisement required.",
      conclusion: "**Address change:**\n\n**Within same district:**\n1. Board resolution\n2. File Form VI within 30 days\n3. Attach: new lease/utility bill\n4. Fee: BDT 500-2,000\n\n**Different district:**\n1. EGM — 75% shareholder resolution\n2. Newspaper advertisement\n3. RJSC approval\n\n📋 Address change docs — ৳199\n📄 Full guide — ৳1,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-009",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["annual return company", "agm rjsc", "বার্ষিক রিটার্ন", "annual compliance company", "company annual filing"],
    question: "What are the annual compliance requirements for a company?",
    irac: {
      issue: "What annual filings must a private limited company make?",
      rule: "Companies Act 1994, S.192: AGM within 120 days of financial year end. Annual return to RJSC within 21 days of AGM. Audited financials required. Income tax return separately to NBR by 15 July.",
      application: "FY ends 31 Dec → AGM by 30 April → Annual return by 21 May → Tax return by 15 July → VAT monthly throughout.",
      conclusion: "**Annual compliance calendar:**\n\n| Deadline | Obligation |\n|---|---|\n| 120 days after FY | Hold AGM |\n| 21 days after AGM | RJSC annual return |\n| 15 July | Income tax return (NBR) |\n| 15th monthly | VAT return (if registered) |\n| Annually | Renew trade licence |\n\n**AGM agenda:**\n• Approve annual accounts\n• Appoint/re-appoint auditor\n• Declare dividend (if any)\n• Director re-election\n\n**Non-compliance:** Penalty + possible strike-off\n\n📄 Annual compliance guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-010",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["increase capital", "increase authorized capital", "শেয়ার মূলধন বৃদ্ধি", "capital increase", "authorized capital"],
    question: "How do I increase my company's share capital?",
    irac: {
      issue: "Process for increasing authorized and paid-up capital?",
      rule: "Companies Act 1994, S.54-56: Requires EGM special resolution (75% shareholders), MOA amendment (Clause V), filing Form V + amended MOA at RJSC, payment of incremental fees.",
      application: "Current authorized capital BDT 10 lakh, want BDT 50 lakh: EGM → special resolution → amend MOA → Form V at RJSC → pay incremental fees.",
      conclusion: "**Capital increase steps:**\n\n1. Check Articles (must permit increase)\n2. EGM — special resolution (75%)\n3. Amend MOA Clause V\n4. File at RJSC:\n   • Form V (increase notice)\n   • Amended MOA\n   • EGM minutes\n5. Pay incremental RJSC fee\n\n**Then issue shares:** Pass allotment resolution + Form IV within 60 days\n\n📄 Capital increase guide — ৳2,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-011",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["transfer shares", "sell shares", "শেয়ার হস্তান্তর", "share transfer procedure", "shares sell"],
    question: "How do I transfer shares in a private limited company?",
    irac: {
      issue: "Legal process for transferring shares in a Bangladesh Pvt Ltd?",
      rule: "Companies Act 1994, S.38: Private company shares restricted by Articles. Typically: right of pre-emption (existing shareholders first right), board approval required. Transfer instrument + share certificate needed. Stamp duty 1.5% of value.",
      application: "Shareholder A sells to outsider B: first offer to existing shareholders → if no takers in 30 days → offer to B → Board approval → execute transfer form → update register → new certificate.",
      conclusion: "**Share transfer:**\n\n1. Check Articles for restrictions\n2. Offer to existing shareholders first (pre-emption)\n3. If no takers → offer to outsider\n4. Board approval\n5. Execute share transfer form\n6. **Stamp duty:** 1.5% of share value\n7. Update share register\n8. Issue new certificate\n9. File Form IV at RJSC within 60 days\n\n📄 Share transfer guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-012",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["dissolve company", "close company", "wind up company", "কোম্পানি বন্ধ", "company dissolution"],
    question: "How do I close or dissolve a company?",
    irac: {
      issue: "Process for voluntarily winding up a company?",
      rule: "Companies Act 1994, S.234-283: Voluntary winding up requires 75% shareholder resolution, liquidator appointment, newspaper advertisement, debt settlement, asset distribution, final RJSC return. Tax clearance from NBR required.",
      application: "Dormant company with no assets/liabilities: apply to RJSC for strike-off (simpler route). Active company with creditors: full voluntary winding up process.",
      conclusion: "**Company dissolution options:**\n\n**Option 1 — Voluntary Winding Up:**\n1. 75% shareholder special resolution\n2. Appoint liquidator\n3. Newspaper advertisement\n4. Settle all debts\n5. Distribute remaining assets\n6. RJSC final return\n\n**Option 2 — Strike Off (dormant):**\n1. Apply to RJSC (no assets/liabilities)\n2. RJSC issues show cause\n3. Strike off completed\n\n**Must have:** Tax clearance from NBR first\n**Time:** 6 months – 2 years\n\n📄 Dissolution guide — ৳3,999",
    },
    escalate: true,
    escalateReason: "Company dissolution requires specialist guidance. WhatsApp NLC.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-013",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["shareholder dispute", "minority shareholder", "শেয়ারহোল্ডার বিরোধ", "oppression mismanagement", "director conflict"],
    question: "What can a minority shareholder do against mismanagement?",
    irac: {
      issue: "Remedies for minority shareholder against oppression or mismanagement?",
      rule: "Companies Act 1994, S.233-234: Minority (min 10% shareholding or 100 members) can petition High Court for relief against oppression/mismanagement. Court can: regulate affairs, compel dividends, order buy-out at fair value, or wind up.",
      application: "Majority directors paying excessive salaries, excluding minority from dividends, hiding accounts = oppression. File petition in High Court Division.",
      conclusion: "**Minority shareholder remedies:**\n\n**Threshold:** 10% shareholding or 100 members\n\n**Court can order:**\n• Regulate company affairs\n• Compel dividend payment\n• Buy out minority at fair value\n• Change board\n• Wind up (last resort)\n\n**Steps:**\n1. Send legal notice to majority/board\n2. Demand accounts inspection\n3. File petition — High Court Division\n\n⚠️ Requires specialist advocate.\n\n📄 Shareholder rights guide — ৳2,999",
    },
    escalate: true,
    escalateReason: "Shareholder disputes need High Court petition. WhatsApp NLC.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-014",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["trade licence", "ট্রেড লাইসেন্স", "business licence", "trade license renewal", "trade licence dhaka"],
    question: "How do I get and renew a trade licence?",
    irac: {
      issue: "Process for obtaining trade licence from city corporation or municipality?",
      rule: "Local Government (City Corporation) Act 2009: Trade licence mandatory for all businesses. Issued by local authority (city corporation/municipality/union parishad). TIN mandatory for city corporation licences. Annual renewal due by 30 June.",
      application: "Apply at ward office of city corporation where business is located. New licence: NID, TIN, lease agreement, photos. Inspector may visit. Renewal: previous year licence + fees.",
      conclusion: "**Trade licence:**\n\n**New application documents:**\n• NID of owner/director\n• TIN certificate\n• Lease agreement\n• Photograph\n• MOA/incorporation cert (for company)\n\n**Process:** Apply → inspector visits → pay fee → licence in 7-30 days\n\n**Renewal deadline:** 30 June each year\n**Late renewal surcharge:** 25% extra\n\n📋 Trade licence docs — ৳99\n📄 Trade licence guide — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-015",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["rjsc certified copy", "company documents copy", "কোম্পানির সার্টিফাইড কপি", "rjsc documents", "certificate copy"],
    question: "How do I get certified copies of company documents from RJSC?",
    irac: {
      issue: "How to obtain certified copies of RJSC company documents?",
      rule: "Companies Act 1994, S.200: RJSC maintains public register. Anyone can inspect or get certified copies. Available online at roc.gov.bd (digitised documents) or physically at RJSC Dhaka.",
      application: "roc.gov.bd → search company → download available documents (if digitised). Fee: BDT 100-500 per document. Physical: visit RJSC, pay counter fee, collect same/next day.",
      conclusion: "**Get RJSC documents:**\n\n**Online (roc.gov.bd):**\n• Create account → search company → download\n• Pay fee online\n\n**Physical (RJSC Dhaka):**\n• Application letter + payment\n• Collect same/next day\n\n**Available:** Certificate of Incorporation, MOA, AOA, annual returns, director list, address\n\n📋 RJSC document guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  // ════════ NEW Q&A 016-050 ════════
  {
    id: "co-qa-016",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["what is moa aoa", "memorandum articles", "এমওএ এওএ", "memorandum association", "articles association"],
    question: "What are MOA and AOA and why are they important?",
    irac: {
      issue: "What are the Memorandum of Association and Articles of Association?",
      rule: "Companies Act 1994, S.6-11: MOA (Memorandum of Association) = company's constitution — defines name, objects, capital, liability. AOA (Articles of Association) = internal rules — governs directors, meetings, shares, dividends. Both filed at RJSC on incorporation.",
      application: "MOA defines what business the company can do. AOA defines how it governs itself internally. A company cannot act outside its MOA objects (ultra vires).",
      conclusion: "**MOA vs AOA:**\n\n**MOA (Memorandum):**\n• Company name\n• Registered office location\n• Objects (what business it can do)\n• Authorized capital\n• Members' liability (limited)\n\n**AOA (Articles):**\n• Share transfer rules\n• Director powers and duties\n• Meeting procedures\n• Dividend rules\n• Voting rights\n\n**Important:** Company cannot do business outside MOA objects. Amend MOA if expanding business.\n\n📄 MOA + AOA drafting — ৳4,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-017",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["bida registration", "foreign investment", "বিদা নিবন্ধন", "bida licence", "foreign investor"],
    question: "What is BIDA registration and when do I need it?",
    irac: {
      issue: "When is BIDA (Bangladesh Investment Development Authority) registration required?",
      rule: "BIDA Act 2016 + Investment Policy 2021: BIDA registration required for: foreign investment in Bangladesh, importing technology, bringing foreign experts, repatriating profits. One-Stop Service (OSS) provides integrated services for investors.",
      application: "Foreign investor forming a BD Pvt Ltd company: needs BIDA registration to legally bring in foreign capital, hire foreign employees, and repatriate profits. Domestic-only companies: BIDA not required (except for specific sectors).",
      conclusion: "**BIDA registration needed for:**\n• Foreign investment in Bangladesh\n• Foreign shareholder in BD company\n• Bringing foreign experts/employees\n• Profit repatriation abroad\n• Branch/liaison office of foreign company\n\n**BIDA One-Stop Service (OSS):**\n• Single window for multiple approvals\n• Work permits, tax exemptions, utility connections\n• Apply: bida.gov.bd\n\n📋 BIDA registration docs — ৳399\n📄 Foreign investment guide — ৳4,999",
    },
    escalate: true,
    escalateReason: "Foreign investment and BIDA registration complex. WhatsApp NLC.",
    relatedRules: ["co-foreign-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-018",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company bank account", "corporate bank account", "কোম্পানির ব্যাংক অ্যাকাউন্ট", "open company account", "business account"],
    question: "How do I open a bank account for my company?",
    irac: {
      issue: "What documents are required to open a corporate bank account in Bangladesh?",
      rule: "Bangladesh Bank KYC Guidelines + Bank-specific requirements: All directors must visit bank (or video KYC). Company account requires: Certificate of Incorporation, MOA/AOA, board resolution authorising account opening and signatories, TIN of company and directors, NID of all directors.",
      application: "After receiving Certificate of Incorporation from RJSC: prepare board resolution for account opening → all directors visit bank → submit documents → account opened in 3-7 working days.",
      conclusion: "**Company bank account — documents:**\n\n• Certificate of Incorporation\n• MOA and AOA\n• Board resolution (account opening + signatories)\n• TIN certificate (company)\n• NID + TIN of all directors\n• Trade licence\n• Recent utility bill (registered office)\n\n**Process:**\n1. All directors visit bank (in-person KYC)\n2. Submit documents\n3. Account opened in 3-7 days\n\n📋 Bank account opening docs — ৳99",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-019",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company not doing business", "dormant company", "নিষ্ক্রিয় কোম্পানি", "dormant rjsc", "company no activity"],
    question: "What happens if my company is not doing any business?",
    irac: {
      issue: "What are the obligations for a dormant or inactive company?",
      rule: "Companies Act 1994: Even dormant companies must file annual returns with RJSC and income tax returns with NBR. Non-filing for multiple years → RJSC sends strike-off notice → company name removed from register if no response.",
      application: "Company formed but no business: still must file nil returns annually at RJSC and NBR. Failing to file = accumulating penalties + risk of strike-off. Better to formally close if not needed.",
      conclusion: "**Dormant company — still must:**\n• File annual return at RJSC (even nil)\n• File income tax return at NBR\n• Pay minimum tax (BDT 3,000-5,000)\n• Maintain registered office\n\n**Consequences of non-filing:**\n• Penalty accumulation\n• RJSC strike-off notice\n• Company struck off register if no response\n\n**Better option:** Formally dissolve company if not needed.\n\n📄 Dormant company guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-020",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["change company name", "rename company", "কোম্পানির নাম পরিবর্তন", "company name change rjsc"],
    question: "How do I change my company's name?",
    irac: {
      issue: "Process for changing a company's registered name?",
      rule: "Companies Act 1994, S.13: Name change requires: special resolution (75% shareholders at EGM), ROC approval/new name clearance, amended Certificate of Incorporation. File Form II + amended MOA at RJSC.",
      application: "Current name 'ABC Trading Ltd' → want 'XYZ Solutions Ltd': get new name clearance → EGM special resolution → file Form II + amended MOA → new Certificate of Incorporation issued.",
      conclusion: "**Company name change:**\n\n1. Get new name clearance from RJSC\n2. Hold EGM — 75% special resolution\n3. File at RJSC:\n   • Form II (change of name)\n   • Amended MOA\n   • EGM minutes\n4. Pay fee\n5. New Certificate of Incorporation issued\n\n**After name change:**\n• Update all letterheads, seals\n• Notify bank, NBR, trade licence authority\n• Update TIN records\n\n📄 Name change guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-021",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company secretary", "company law compliant", "কোম্পানি সেক্রেটারি", "cs officer", "company secretary requirement"],
    question: "Does my company need a Company Secretary?",
    irac: {
      issue: "When is a Company Secretary mandatory under Bangladesh company law?",
      rule: "Companies Act 1994, S.161: Public limited companies with paid-up capital above BDT 2 crore must appoint a qualified Company Secretary. Private limited companies: no mandatory requirement, but good practice. Listed companies: Company Secretary mandatory (BSEC rules).",
      application: "Small private limited company: no legal requirement for Company Secretary. Large private company or listed company: mandatory. Company Secretary handles RJSC filings, board minutes, compliance calendar.",
      conclusion: "**Company Secretary requirement:**\n\n**Mandatory:**\n• Public limited company (paid-up > BDT 2 crore)\n• Listed companies (BSEC rule)\n\n**Not mandatory but recommended:**\n• Large private limited companies\n• Companies with complex compliance\n\n**What CS does:**\n• RJSC filings and returns\n• Board/AGM minutes\n• Compliance calendar\n• Shareholder communications\n\n📄 Compliance officer guide — ৳999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-022",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["dividend declaration", "declare dividend", "লভ্যাংশ", "dividend pay company", "dividend procedure"],
    question: "How does a company declare and pay dividends?",
    irac: {
      issue: "What is the process for declaring and paying dividends in a Bangladesh company?",
      rule: "Companies Act 1994, S.137: Dividends declared by shareholders at AGM based on board recommendation. Board recommends dividend from distributable profits (after tax). Interim dividend can be declared by board between AGMs. WHT on dividend: 10% (listed), 20% (unlisted) deducted before payment.",
      application: "Company has BDT 50 lakh distributable profit. Board recommends 30% dividend on BDT 10 lakh paid-up capital = BDT 3 lakh total dividend. AGM approves. Deduct WHT 20% = BDT 60,000 to NBR. Pay net BDT 2,40,000 to shareholders.",
      conclusion: "**Dividend declaration process:**\n\n1. Board recommends dividend amount\n2. AGM approves (ordinary resolution)\n3. Set payment date (max 42 days after declaration)\n4. Deduct WHT (10% listed / 20% unlisted)\n5. Deposit WHT with NBR within 7 days\n6. Pay net dividend to shareholders\n7. Update dividend register\n\n**No dividends** if: accumulated losses, insufficient profits\n\n📄 Dividend procedure guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-023",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company audit", "auditor appointment", "অডিটর নিয়োগ", "company auditor", "audit requirement"],
    question: "When does a company need an auditor?",
    irac: {
      issue: "What are the audit requirements for companies under Companies Act 1994?",
      rule: "Companies Act 1994, S.210-213: Every company with paid-up capital above BDT 1 crore must have audited financial statements. Auditor appointed at AGM. Must be a Chartered Accountant (CA) registered with ICAB. Auditor files report with annual return.",
      application: "Small company with paid-up capital BDT 50,000: no mandatory audit. Company with BDT 50 lakh paid-up capital: mandatory annual audit by CA firm. Banks require audited accounts for loans regardless of audit requirement.",
      conclusion: "**Audit requirements:**\n\n**Mandatory audit:** Paid-up capital > BDT 1 crore\n**Auditor:** Chartered Accountant (CA) from ICAB\n**Appointment:** At AGM each year\n**Report:** Filed with RJSC annual return\n\n**Even if not mandatory:**\n• Banks require for loans\n• NBR may require for tax audit\n• Foreign investors require for due diligence\n\n📄 Audit requirements guide — ৳999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-024",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company loan", "company borrowing", "কোম্পানি ঋণ", "company bank loan", "business loan"],
    question: "Can a company take a bank loan and what documents are needed?",
    irac: {
      issue: "What documentation does a company need to take a bank loan?",
      rule: "Bank Company Act 1991 + Bangladesh Bank guidelines + Companies Act 1994: Companies can borrow from banks by executing security documents (mortgage, charge). Board resolution authorising borrowing and appointing authorised signatory required. Security: land mortgage, hypothecation of assets, personal guarantee of directors.",
      application: "Company wants BDT 1 crore loan: Board resolution → apply at bank → bank due diligence → execute security documents → loan disbursed. Directors' personal guarantee often required for small/medium companies.",
      conclusion: "**Company bank loan — documents:**\n\n• Certificate of Incorporation\n• MOA/AOA\n• Board resolution (borrowing authority)\n• Audited financial statements (2-3 years)\n• TIN + trade licence\n• NID of all directors\n• Security documents (mortgage/hypothecation)\n• Personal guarantee of directors\n• Tax return acknowledgements\n\n**Types of security accepted:**\n• Land/property mortgage\n• Hypothecation of stock/equipment\n• FDR pledge\n\n📄 Company loan guide — ৳1,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-025",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company penalty rjsc", "rjsc fine", "কোম্পানি জরিমানা", "non-filing penalty", "company compliance penalty"],
    question: "What are the penalties for non-compliance with RJSC?",
    irac: {
      issue: "What penalties apply for failure to comply with RJSC filing requirements?",
      rule: "Companies Act 1994: Non-filing annual return: BDT 1,000 per month per director. Non-holding AGM: BDT 5,000 per director per day. Late filing of other forms: BDT 1,000 + additional per day. Continued defaults: RJSC can strike off company.",
      application: "Company fails to file annual return for 2 years with 2 directors: BDT 1,000 × 24 months × 2 directors = BDT 48,000 penalty (just for annual return). Penalties accumulate quickly.",
      conclusion: "**RJSC non-compliance penalties:**\n\n| Default | Penalty |\n|---|---|\n| Annual return late | BDT 1,000/month/director |\n| AGM not held | BDT 5,000/day/director |\n| Late Form filing | BDT 1,000 + daily |\n| False statement | Up to BDT 50,000 |\n| Continued defaults | Strike-off |\n\n⚠️ Penalties accumulate rapidly — file even if late.\n\n📄 RJSC compliance guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-026",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["merger acquisition", "company merger", "কোম্পানি একীভূত", "amalgamation", "takeover bangladesh"],
    question: "How do companies merge or get acquired in Bangladesh?",
    irac: {
      issue: "What is the legal process for company mergers and acquisitions in Bangladesh?",
      rule: "Companies Act 1994, S.228-233: Merger (amalgamation) requires: scheme of arrangement approved by shareholders (75%), creditor approval, High Court sanction. Share acquisition: buy majority shares from existing shareholders — simpler, no court approval needed.",
      application: "Full merger: complex court process (6-18 months). Share acquisition (takeover): buy shares from shareholders → much faster → practical for most M&A in Bangladesh.",
      conclusion: "**M&A options:**\n\n**Share acquisition (faster):**\n• Buy majority shares from shareholders\n• No court approval needed\n• Share transfer process + RJSC Form IV\n• Time: 1-3 months\n\n**Merger/Amalgamation (formal):**\n• Scheme of arrangement\n• 75% shareholder + creditor approval\n• High Court sanction\n• Time: 6-18 months\n\n⚠️ Engage M&A specialist for due diligence.\n\n📄 M&A guide — ৳4,999",
    },
    escalate: true,
    escalateReason: "Mergers and acquisitions require specialist legal guidance. WhatsApp NLC.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-027",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["epz company", "sez", "export processing zone", "ইপিজেড কোম্পানি", "beza"],
    question: "Can I register a company in EPZ or SEZ?",
    irac: {
      issue: "What are the benefits and process for registering a company in Bangladesh EPZ or SEZ?",
      rule: "Bangladesh Export Processing Zones Authority (BEPZA) Act 1980 + Bangladesh Economic Zones Act 2010: Companies in EPZ (Export Processing Zones) and SEZ (Special Economic Zones) receive special tax exemptions, duty-free imports, and regulatory facilitation. BEPZA/BEZA approvals required instead of standard RJSC in some cases.",
      application: "Manufacturing company wanting to export 100%: EPZ company gets 100% duty-free import of raw materials, 10-year tax holiday, no work permit fee for foreign employees. Suitable for garments, electronics manufacturing.",
      conclusion: "**EPZ/SEZ company benefits:**\n\n✅ **Tax holiday:** 10 years (Type A — 100% export)\n✅ **Duty-free imports:** Raw materials, machinery\n✅ **No work permit fee:** Foreign workers\n✅ **VAT/customs exemption**\n✅ **100% foreign ownership allowed**\n\n**Apply to:**\n• EPZ: BEPZA (bepza.gov.bd)\n• SEZ: BEZA (beza.gov.bd)\n\n📄 EPZ/SEZ registration guide — ৳4,999",
    },
    escalate: true,
    escalateReason: "EPZ/SEZ registration is complex. WhatsApp NLC for specialist guidance.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-028",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company striking off", "struck off company", "কোম্পানি বাতিল", "restore struck company", "company removed register"],
    question: "My company was struck off by RJSC — can I restore it?",
    irac: {
      issue: "Can a company struck off the RJSC register be restored?",
      rule: "Companies Act 1994, S.396: A company struck off the register can be restored within 20 years by applying to High Court. Court orders restoration if: company was carrying on business at time of strike-off, or it is just and equitable to restore. All outstanding returns and penalties must be paid.",
      application: "Company struck off for non-filing: apply to High Court Division → pay all outstanding filing fees and penalties → court orders RJSC to restore → company back on register.",
      conclusion: "**Restore struck-off company:**\n\n1. Apply to High Court Division\n2. Show company was active OR just/equitable to restore\n3. Pay ALL outstanding RJSC fees + penalties\n4. File all overdue annual returns\n5. Court order → RJSC restores company\n\n**Time limit:** 20 years from strike-off\n\n⚠️ All penalties and back-filings must be cleared.\n\n📄 Restoration guide — ৳2,999",
    },
    escalate: true,
    escalateReason: "Company restoration requires High Court application. WhatsApp NLC.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-029",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["ngo registration", "society registration", "এনজিও নিবন্ধন", "society act", "nonprofit registration"],
    question: "How do I register an NGO or society in Bangladesh?",
    irac: {
      issue: "What are the options for registering a non-profit organization in Bangladesh?",
      rule: "Societies Registration Act 1860 + NGO Affairs Bureau Rules + Voluntary Social Welfare Agencies Ordinance 1961: NGO options: (1) Society under Societies Registration Act at District Commissioner's office, (2) Trust under Trust Act 1882, (3) Company limited by guarantee under Companies Act 1994, (4) Registration with NGO Affairs Bureau for foreign-funded NGOs.",
      application: "Local community NGO: register as Society with DC office. NGO receiving foreign grants: mandatory registration with NGO Affairs Bureau (Prime Minister's Office) for foreign funding permission.",
      conclusion: "**NGO/Society registration options:**\n\n**Society (Societies Act 1860):**\n• Register at DC office (district)\n• Min 7 members\n• General/charitable purposes\n\n**Trust (Trust Act 1882):**\n• Register at Sub-Registry office\n• Specific charitable purpose\n\n**NGO Bureau (foreign-funded):**\n• Mandatory for foreign grants\n• Apply: ngoab.gov.bd\n• Annual activity report required\n\n📋 NGO registration docs — ৳299\n📄 NGO setup guide — ৳2,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-030",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["startup registration", "startup company", "স্টার্টআপ", "startup bangladesh", "new business register"],
    question: "What is the easiest way to legally register a startup in Bangladesh?",
    irac: {
      issue: "What is the fastest and simplest legal structure for a startup in Bangladesh?",
      rule: "Companies Act 1994 + OPC Rules 2020 + Bangladesh Startup Policy 2021: Options for startups: OPC (solo founder, limited liability), Private Limited (2+ founders), Proprietorship (sole trader, no RJSC needed). Bangladesh Startup Policy 2021 provides startup ecosystem support through ICT Division and startup.gov.bd.",
      application: "Solo tech founder: OPC is fastest (2 weeks, full online, limited liability). Two co-founders: Private Limited (3 weeks). Solo with no need for limited liability and minimal compliance: Proprietorship (trade licence only, no RJSC needed).",
      conclusion: "**Startup registration options:**\n\n**Fastest (solo):** OPC\n• 2 weeks, full online at roc.gov.bd\n• Limited liability\n• Single TIN + NID needed\n\n**Two+ founders:** Private Limited\n• 3 weeks at roc.gov.bd\n• Industry standard for investor funding\n\n**No RJSC needed:** Sole Proprietorship\n• Just trade licence\n• No limited liability\n• Simplest but least protection\n\n**Startup support:** startup.gov.bd (ICT Division)\n\n📄 Startup registration guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001", "co-opc-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-031",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company resolution", "board resolution", "পরিচালনা পর্ষদের সিদ্ধান্ত", "board minutes", "resolution pass"],
    question: "What is a board resolution and when is it needed?",
    irac: {
      issue: "When must a company pass a board resolution and what are the requirements?",
      rule: "Companies Act 1994 + Articles of Association: Board resolutions are formal decisions by directors at a board meeting. Required for: opening bank accounts, authorising signatories, taking loans, major contracts, appointing staff, RJSC filings. Quorum requirement in AOA (usually majority of directors).",
      application: "Company wants to open bank account: Board resolution must authorise which directors can sign cheques. Company takes loan: Board resolution authorises the borrowing and security creation.",
      conclusion: "**Board resolution needed for:**\n\n• Opening/changing bank account\n• Authorising signatories\n• Taking loans or creating security\n• Major contracts above a threshold\n• RJSC form filings\n• Appointing key staff\n• Dividend recommendation\n\n**Format:** Date, attendance, resolution text, signatures\n**Quorum:** Usually majority directors (per AOA)\n**Must be:** Recorded in Board Minutes Book\n\n📄 Board resolution templates — ৳999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-032",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company seal", "common seal", "কোম্পানির সিল", "company stamp", "seal requirement"],
    question: "Does my company need a common seal?",
    irac: {
      issue: "Is a common seal mandatory for a Bangladesh company?",
      rule: "Companies Act 1994, S.40: Every company must have a common seal with its name engraved on it. The seal must be affixed to share certificates, debentures, powers of attorney, and certain formal documents. Seal affixed in presence of at least one director and countersigned.",
      application: "Company must get a metal seal made with company name. Affix on share certificates, property deed powers of attorney. Modern practice: many documents now use authorised signatures instead of seal for routine matters.",
      conclusion: "**Company common seal:**\n\n**Mandatory:** Yes — must have company name engraved\n\n**Required on:**\n• Share certificates\n• Debentures\n• Powers of attorney\n• Formal property documents\n\n**Affixing:** In presence of 1+ director, countersigned\n\n**Get made at:** Any rubber/metal stamp maker\n**Cost:** BDT 500-2,000\n\n📋 Company formation checklist — ৳199",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-033",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company contract", "director contract", "পরিচালক চুক্তি", "director service agreement", "managing director"],
    question: "Can a director be an employee of the company?",
    irac: {
      issue: "Can directors also be employed by the company and receive salary?",
      rule: "Companies Act 1994, S.93-95: A director can also serve as Managing Director (MD) or executive director under a service contract. Service contract must be approved by shareholders if over 5 years. Salary of executive directors is an allowable expense for the company (deductible for tax). Non-executive directors can receive only fees approved at AGM.",
      application: "Company has 2 directors. Both also work full-time for the company as CEO and CFO. Both receive salary under service contracts. Salary = deductible expense for company. Must be approved by board and disclosed to shareholders.",
      conclusion: "**Director as employee:**\n\n✅ **Allowed:** Director can be employed (executive director/MD)\n✅ **Salary:** Deductible company expense\n✅ **Service contract:** Up to 5 years (shareholder approval for longer)\n\n**Non-executive director:**\n• Receives sitting fees only (not salary)\n• Fees approved at AGM\n\n**Disclosure:** Salary of directors disclosed in annual report/accounts\n\n📄 Director service contract — ৳2,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-034",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["intellectual property company", "patent trademark", "বৌদ্ধিক সম্পদ", "trademark registration", "copyright company"],
    question: "How does a company protect its brand and intellectual property?",
    irac: {
      issue: "What IP protections are available for companies in Bangladesh?",
      rule: "Trademarks Act 2009: Register trademark with Department of Patents, Designs and Trademarks (DPDT). Patents and Designs Act 2022: Register patents and industrial designs with DPDT. Copyright Act 2000: Automatic on creation, optional registration with Copyright Office. Company name registration at RJSC does NOT protect the brand — separate trademark registration needed.",
      application: "Company 'TechBD Ltd' incorporated at RJSC: company name registered. But brand name 'TechBD' is not protected until trademark registered separately at DPDT. Another company could use the same brand name.",
      conclusion: "**IP protection for companies:**\n\n**Trademark (brand name/logo):**\n• Register at DPDT (dpdt.gov.bd)\n• Class-based system (45 classes)\n• Protection: 10 years (renewable)\n• Cost: ~BDT 4,000-10,000 per class\n\n**Patent (invention):**\n• Register at DPDT\n• Protection: 16-20 years\n\n**Copyright (software, content):**\n• Automatic on creation\n• Register at Copyright Office for evidence\n\n⚠️ RJSC company name ≠ trademark protection.\n\n📄 IP registration guide — ৳1,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-035",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company director liability", "director personal liability", "পরিচালকের দায়", "director sued personally", "limited liability"],
    question: "Can a company director be personally liable for company debts?",
    irac: {
      issue: "When can a director be held personally liable for a company's debts?",
      rule: "Companies Act 1994: Limited liability means shareholders/directors not normally liable for company debts beyond their investment. Exceptions: director personally guaranteed a loan, fraudulent trading (director knew company was insolvent), wrongful trading, tax evasion by director, signing false statements to RJSC.",
      application: "Company cannot pay bank loan: bank cannot normally sue director personally — limited liability protects them. BUT if director personally guaranteed the loan: bank can sue director personally for the full amount.",
      conclusion: "**Director personal liability — exceptions:**\n\n**Normally:** Limited liability protects directors.\n\n**Director can be personally liable if:**\n• Signed personal guarantee for company loan\n• Fraudulent trading (insolvent company continuing)\n• Tax evasion through the company\n• False statements to RJSC\n• Lifting corporate veil (court discretion)\n\n⚠️ Never sign personal guarantee without understanding consequences.\n\n📄 Director liability guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-036",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["microfinance license", "mfi license", "মাইক্রোফাইন্যান্স লাইসেন্স", "ngo microfinance", "mra license"],
    question: "How does an NGO get a microfinance licence?",
    irac: {
      issue: "What is required to operate microfinance activities in Bangladesh?",
      rule: "Microcredit Regulatory Authority (MRA) Act 2006: All NGOs and organisations conducting microfinance activities must obtain MRA licence. Apply to MRA with: NGO registration, audited accounts, business plan, security deposit. MRA regulates interest rates and reporting.",
      application: "Existing registered NGO wanting to offer microcredit to rural women: apply to MRA for microfinance licence. Without MRA licence, microfinance operations are illegal.",
      conclusion: "**Microfinance licence (MRA):**\n\n**Who must apply:** Any NGO/org offering microcredit\n\n**Requirements:**\n• Existing NGO registration\n• Audited financial statements\n• Business plan\n• Security deposit with MRA\n• Clean governance record\n\n**Apply to:** Microcredit Regulatory Authority (mra.gov.bd)\n\n**Processing:** 3-6 months\n\n📄 MRA licence guide — ৳2,999",
    },
    escalate: true,
    escalateReason: "MRA licence application is complex. WhatsApp NLC for guidance.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-037",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company accounts", "financial statements", "কোম্পানির হিসাব", "balance sheet requirement", "company accounts requirement"],
    question: "What financial records must a company maintain?",
    irac: {
      issue: "What books of accounts and financial records must companies maintain?",
      rule: "Companies Act 1994, S.181-183: Companies must maintain: cash book, ledger, journal, stock register. Financial statements: balance sheet, profit & loss account, cash flow statement. Records kept at registered office. Inspection right: any member can inspect during business hours.",
      application: "Private limited company: maintain complete books of accounts. Get audited annually if required. Store at registered office for at least 6 years.",
      conclusion: "**Mandatory financial records:**\n\n**Books of accounts:**\n• Cash book\n• General ledger\n• Journal\n• Stock/inventory register\n• Fixed assets register\n\n**Annual financial statements:**\n• Balance sheet\n• Profit & loss account\n• Cash flow statement\n• Notes to accounts\n\n**Retention:** Minimum 6 years\n**Location:** Registered office\n**Members' right:** Inspect accounts during business hours\n\n📄 Accounting compliance guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-038",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company insolvency", "company bankrupt", "কোম্পানি দেউলিয়া", "insolvent company", "company cannot pay debts"],
    question: "What happens when a company cannot pay its debts?",
    irac: {
      issue: "What legal process applies when a company is insolvent in Bangladesh?",
      rule: "Companies Act 1994, S.241-283: Creditor can apply to High Court for compulsory winding up if company cannot pay debts above BDT 500. Court appoints official receiver/liquidator. Liquidator sells assets, pays creditors in priority order: secured creditors first, then employees' dues, then unsecured creditors, then shareholders.",
      application: "Company owes BDT 50 lakh to bank and BDT 10 lakh to suppliers, has only BDT 20 lakh assets: bank (secured) paid first. If insufficient: suppliers get proportional share. Shareholders get nothing.",
      conclusion: "**Company insolvency — creditor priority:**\n\n1. **Secured creditors** (mortgage holders)\n2. **Liquidation costs**\n3. **Employee wages/gratuity**\n4. **Government dues** (tax, VAT)\n5. **Unsecured creditors** (suppliers etc.)\n6. **Shareholders** (last — often get nothing)\n\n**Creditor winding up:** Creditor applies to High Court if debt > BDT 500 unpaid 21 days after demand.\n\n⚠️ Directors can be liable if fraudulent trading proven.\n\n📄 Insolvency guide — ৳2,999",
    },
    escalate: true,
    escalateReason: "Company insolvency requires urgent specialist advice. WhatsApp NLC.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-039",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["public limited company", "go public", "list stock exchange", "পাবলিক কোম্পানি", "dse listing"],
    question: "How does a private company become a public listed company?",
    irac: {
      issue: "What is the process for converting a private limited company to a public listed company?",
      rule: "Companies Act 1994 + Bangladesh Securities and Exchange Commission (Public Issue) Rules 2015: Conversion: private → public company (RJSC: remove private restriction from MOA/AOA, notify RJSC). Then apply to BSEC for IPO approval. List on DSE or CSE. Minimum requirements: 3 years operation, positive net worth, audited accounts.",
      application: "Company operating 5 years with BDT 20 crore turnover: can apply for IPO. BSEC reviews financials, approves IPO prospectus. Shares offered to public. Listed on DSE → tax rate drops from 27.5% to 22.5%.",
      conclusion: "**Going public — process:**\n\n1. Convert: Pvt Ltd → Public Ltd (RJSC)\n2. Appoint Issue Manager (investment bank)\n3. Prepare IPO prospectus\n4. BSEC approval (3-6 months)\n5. Public subscription\n6. List on DSE or CSE\n\n**Minimum requirements:**\n• 3 years operation\n• Positive net assets\n• Audited accounts (3 years)\n• Clean regulatory history\n\n**Benefit:** Tax rate 22.5% vs 27.5%\n\n📄 IPO guide — ৳9,999",
    },
    escalate: true,
    escalateReason: "IPO/listing process requires investment bank and legal counsel. WhatsApp NLC.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-040",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company registered agent", "rjsc agent", "company formation agent", "কোম্পানি গঠন এজেন্ট", "rjsc service"],
    question: "Can someone else register my company on my behalf?",
    irac: {
      issue: "Can a lawyer or agent handle RJSC company registration on behalf of the applicant?",
      rule: "Companies Act 1994 + RJSC Rules: Company registration can be done by the founders themselves or by an authorized agent (lawyer, CA, or company formation agent). Power of attorney or authorization letter required. Subscribers must sign MOA and AOA personally (e-signature now accepted on RJSC portal).",
      application: "Busy entrepreneur outside Dhaka: can authorize NLC/CA to prepare all documents and file online. Founders sign MOA/AOA (physical or e-signature). NLC handles RJSC portal submission.",
      conclusion: "**Company registration by agent:**\n\n✅ **Allowed:** Lawyer, CA, or formation agent can file\n✅ **Online:** roc.gov.bd supports e-filing\n✅ **Authorization:** Written authorization or POA needed\n\n**Founders must still:**\n• Sign MOA and AOA (physical or e-signature)\n• Be present for bank KYC (cannot delegate)\n\n**NLC service:** Full company registration including MOA/AOA drafting, RJSC filing, TIN registration.\n\n📄 Full registration service — ৳4,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-041",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company buy property", "company purchase land", "কোম্পানি জমি কেনা", "company property acquisition", "corporate property"],
    question: "Can a company buy land or property in Bangladesh?",
    irac: {
      issue: "Can a registered company purchase immovable property in Bangladesh?",
      rule: "Transfer of Property Act 1882 + Companies Act 1994: A registered company as a legal entity can buy, sell, and hold immovable property in its own name. Property deed registered in company name. Company's authorized persons (directors per board resolution) sign the deed.",
      application: "Company buys office space in Dhaka: Board resolution authorising purchase and specifying signatories → directors sign sale deed → registered at Sub-Registry → property in company name.",
      conclusion: "**Company buying property:**\n\n✅ **Allowed:** Company can own property in its name\n\n**Requirements:**\n• Board resolution authorising purchase\n• Specify authorized signatories for deed\n• TIN certificate of company\n• Certificate of Incorporation\n• Pay AIT, stamp duty, registration fee\n\n**After purchase:**\n• Property mutation in company name\n• Property shown as asset in company accounts\n\n📄 Corporate property guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-042",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company not registered", "unregistered business", "অনিবন্ধিত ব্যবসা", "no registration business", "informal business"],
    question: "What are the risks of running a business without registration?",
    irac: {
      issue: "What legal risks exist for operating an unregistered business in Bangladesh?",
      rule: "Companies Act 1994 + Partnership Act 1932 + Income Tax Act 2023: Operating a business without required registration: trade licence violation (local government fine), TIN violation, income tax evasion exposure. Unregistered firm cannot sue in court. No limited liability protection for owners.",
      application: "Running a small business from home with trade licence only: legal for small-scale. Adding staff, dealing with banks, importing: trade licence alone insufficient. Company formation or firm registration needed.",
      conclusion: "**Risks of no formal registration:**\n\n❌ Cannot sue or defend in court (no legal standing)\n❌ No limited liability — personal assets at risk\n❌ Cannot open proper business bank account\n❌ Cannot bid for government contracts\n❌ Cannot raise investment/loans formally\n❌ Tax evasion risk if income not declared\n❌ Trade licence violation fines\n\n**Minimum for formal business:**\n• Trade licence (all businesses)\n• TIN (income above threshold)\n• RJSC registration (for legal entity)\n\n📄 Business formalisation guide — ৳999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-043",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company name reserved", "rjsc name reserve", "নাম সংরক্ষণ", "name clearance expired", "name reservation"],
    question: "How long is my company name reserved after clearance?",
    irac: {
      issue: "For how long is RJSC name clearance valid and what happens if it expires?",
      rule: "RJSC Rules: Name clearance is valid for 90 days from the date of approval. If incorporation is not completed within 90 days, the name clearance expires. A new name clearance application must be filed — there is no guarantee the same name will be available again.",
      application: "Got name clearance for 'InnovateBD Ltd' on 1 January: must complete incorporation by 31 March. If missed: reapply for name clearance — another company may have already taken the name.",
      conclusion: "**Name clearance validity: 90 days**\n\n⚠️ Must incorporate within 90 days or clearance expires.\n\n**If expired:**\n• Reapply for name clearance\n• No guarantee same name available\n• Another company may have used it\n\n**Practical advice:**\n• Apply for name clearance only when ready to incorporate\n• Start MOA/AOA drafting immediately after clearance\n\n📋 Name clearance guide — ৳99",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-044",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company employee rights", "worker rights company", "কর্মচারী অধিকার", "employee company law", "termination company"],
    question: "What are employee rights in a company under Bangladesh law?",
    irac: {
      issue: "What labour rights do employees of a company have under Bangladesh law?",
      rule: "Bangladesh Labour Act 2006 (amended 2018) + Labour Rules 2015: All employees have rights to: written appointment letter, gratuity (1 month per year after 5 years), provident fund (if company has 100+ workers), annual leave (10 days paid), sick leave (14 days), maternity leave (16 weeks), festival bonus (2 per year), termination notice/payment.",
      application: "Company cannot terminate employee without notice or pay: minimum 1 month notice or payment in lieu. After 5 years: gratuity = last month's basic salary × number of years.",
      conclusion: "**Employee rights — Bangladesh Labour Act 2006:**\n\n• Written appointment letter — mandatory\n• Annual leave — 10 days paid\n• Sick leave — 14 days\n• Maternity leave — 16 weeks (full pay)\n• Festival bonus — 2 per year (equivalent to 1 month basic each)\n• Gratuity — 1 month basic × years served (after 5 years)\n• Notice on termination — 1 month or payment in lieu\n\n📄 Labour compliance guide — ৳1,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-045",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["rjsc online system", "roc.gov.bd", "rjsc portal", "আরজেএসসি অনলাইন", "online company registration"],
    question: "How does the RJSC online registration system work?",
    irac: {
      issue: "What services are available on the RJSC online portal (roc.gov.bd)?",
      rule: "RJSC Automation Project: roc.gov.bd provides online services for: name clearance, company incorporation, annual return filing, form submissions, certified document downloads, company search. Payment via Sonali Bank sePay, SSL Commerz. Physical RJSC visit no longer required for most services.",
      application: "Entrepreneur in Sylhet can incorporate a Dhaka company fully online without visiting Dhaka: name clearance → MOA/AOA upload → payment → Certificate of Incorporation delivered online.",
      conclusion: "**RJSC online portal (roc.gov.bd):**\n\n**Services available online:**\n• Name clearance application\n• Company incorporation\n• Annual return filing\n• Form XII, V, VI, IV etc.\n• Document download\n• Company search\n• Fee payment\n\n**Payment:** Sonali Bank sePay, SSL Commerz\n**Support:** RJSC helpline 16516\n\n**No longer needed:** Physical RJSC visit for most services.\n\n📋 RJSC online guide — ৳99",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-046",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company formation cost", "incorporation cost", "কোম্পানি গঠনে খরচ", "rjsc fee", "registration fee company"],
    question: "How much does it cost to register a company in Bangladesh?",
    irac: {
      issue: "What are the total costs for incorporating a private limited company?",
      rule: "RJSC Fee Schedule (2024): RJSC registration fee based on authorized capital: up to BDT 1 lakh capital = BDT 3,200 fee. BDT 1 lakh – 5 lakh = BDT 5,000. BDT 5 lakh – 1 crore = BDT 10,000. BDT 1 crore – 5 crore = BDT 20,000. Plus stamp duty on MOA/AOA.",
      application: "Company with BDT 10 lakh authorized capital: RJSC fee ~BDT 7,000 + MOA/AOA stamp + lawyer/CA fees. Total typically BDT 15,000-30,000 for basic incorporation (government fees + professional fees).",
      conclusion: "**Company registration cost (approx):**\n\n| Item | Cost |\n|---|---|\n| RJSC registration fee | BDT 3,200–20,000+ |\n| Stamp duty on MOA/AOA | BDT 500-2,000 |\n| TIN registration | Free |\n| Trade licence | BDT 1,000-5,000 |\n| Professional fees (lawyer/CA) | BDT 5,000-20,000 |\n| **Total approx.** | **BDT 15,000-50,000** |\n\nRJSC fee based on authorized capital amount.\n\n📄 Full formation cost breakdown — ৳299",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-047",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company password rjsc", "rjsc account login", "আরজেএসসি পাসওয়ার্ড", "roc account reset", "rjsc login"],
    question: "I lost access to my RJSC portal account — how do I recover it?",
    irac: {
      issue: "How to recover or reset RJSC (roc.gov.bd) portal account access?",
      rule: "RJSC IT System: roc.gov.bd accounts can be recovered via: (1) password reset link sent to registered email, (2) contacting RJSC IT helpdesk with company registration number and NID verification, (3) physical visit to RJSC Dhaka with NID and incorporation documents.",
      application: "Lost RJSC login: try email password reset first. If email access also lost: call RJSC helpline 16516 or visit RJSC Dhaka with NID and Certificate of Incorporation for identity verification.",
      conclusion: "**RJSC account recovery:**\n\n1. **Try:** Forgot password → email reset at roc.gov.bd\n2. **If email lost:** Call RJSC helpline **16516**\n3. **Physical option:** Visit RJSC Dhaka\n   • Bring: NID + Certificate of Incorporation\n   • Account verified and reset\n\n**RJSC Dhaka address:**\nRJSC Bhaban, TCB Bhaban\n1 Karwan Bazar, Dhaka 1215\n\n📋 RJSC account recovery guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-048",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company nominee director", "opc nominee", "নমিনি পরিচালক", "nominee director requirement", "backup director"],
    question: "What is a nominee director in a One Person Company?",
    irac: {
      issue: "What is the role of a nominee director in an OPC?",
      rule: "One Person Company Rules 2020: OPC must nominate a person (nominee director) who will take over the company if the sole member dies or becomes incapacitated. Nominee must be a Bangladeshi resident. Nominee's details filed with RJSC. Nominee does not have any management role while sole member is active.",
      application: "OPC sole member names his wife as nominee director: if sole member dies, wife automatically takes over the OPC. Nominee's NID and consent filed at RJSC during incorporation.",
      conclusion: "**OPC Nominee Director:**\n\n**Purpose:** Succession plan — takes over if sole member dies/incapacitated\n\n**Requirements:**\n• Bangladeshi resident\n• NID copy\n• Written consent (Form OPC-1)\n• Filed with RJSC at incorporation\n\n**Active role:** None while sole member is alive/capable\n**Triggered by:** Death or legal incapacity of sole member\n\n**Change nominee:** File Form OPC-2 at RJSC\n\n📋 OPC guide — ৳299",
    },
    escalate: false,
    relatedRules: ["co-opc-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-049",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["company objects change", "moa amendment objects", "ব্যবসার উদ্দেশ্য পরিবর্তন", "change business objects", "new business activity"],
    question: "Can I add a new business activity to my existing company?",
    irac: {
      issue: "How to add or change business objects in a company's MOA?",
      rule: "Companies Act 1994, S.12: Objects of the company defined in MOA Clause III. Company cannot carry out activities outside its stated objects (ultra vires). Adding new objects: requires special resolution at EGM (75% shareholders), amended MOA filed at RJSC.",
      application: "Trading company wants to add IT services: EGM → 75% special resolution → amend MOA Clause III → file amended MOA at RJSC → can now legally conduct IT business.",
      conclusion: "**Add new business activity:**\n\n1. Hold EGM — 75% special resolution\n2. Amend MOA Clause III (objects)\n3. File at RJSC:\n   • Amended MOA\n   • EGM minutes\n   • Form I\n4. Pay filing fee\n5. New activity now authorised\n\n⚠️ Conducting business outside MOA objects = ultra vires = illegal contract.\n\n**Practical tip:** Draft initial MOA with broad objects to avoid future amendments.\n\n📄 MOA amendment guide — ৳1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "co-qa-050",
    area: "company",
    jurisdiction: "BD",
    triggerKeywords: ["nlc company service", "rjsc service nlc", "কোম্পানি গঠন সেবা", "company registration help", "professional company setup"],
    question: "What company law services does NLC provide?",
    irac: {
      issue: "What corporate and commercial legal services does Neum Lex Counsel offer?",
      rule: "Neum Lex Counsel (NLC) is a Bangladesh legal and corporate compliance practice headed by Nazmul, Advocate, Supreme Court of Bangladesh. NLC specialises in RJSC corporate compliance using the ILRMF (Institutional Legal Rule Management Framework) system.",
      application: "NLC handles all corporate lifecycle work from formation to dissolution, including RJSC filings, shareholder agreements, foreign company registration, BIDA compliance, and corporate dispute resolution.",
      conclusion: "**NLC Corporate Law Services:**\n\n✅ Company formation (Pvt Ltd, OPC, Partnership)\n✅ MOA & AOA drafting\n✅ RJSC all filings (annual returns, changes)\n✅ Foreign company / BIDA registration\n✅ Share transfer and capital restructuring\n✅ Shareholder agreements\n✅ Company dissolution\n✅ Corporate dispute resolution\n✅ Trade licence and regulatory compliance\n\n**Contact NLC:**\nWhatsApp to Nazmul for consultation.\n\n**Response time:** Within 24 hours.",
    },
    escalate: true,
    escalateReason: "Contact NLC directly for company law services. WhatsApp Nazmul.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
];

const companyModule: KnowledgeModule = {
  area: "company",
  label: "Company & Commercial Law — RJSC 2024",
  description: "50 Q&A covering private limited companies, OPC, partnerships, foreign company, BIDA, annual compliance, share transfers, trade licence, dissolution, and RJSC procedures — all current 2024 rules.",
  rules,
  qaBank,
};

export default companyModule;
