// ─── JesAI Criminal Law Knowledge Module ─────────────────────
// NLC validated — Nazmul, Advocate, Supreme Court of Bangladesh
// Covers: Penal Code 1860, CrPC 1898, Evidence Act 1872
// Special Laws: Nari O Shishu 2000, Cyber Security Act 2023,
// Narcotics Control Act 2018, Torture Prevention Act 2013
// Audience: Law students, bar exam, general citizens
// Last verified: 2025-03-09

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "cr-murder-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Murder — Section 302, Penal Code 1860",
    rule: "Whoever commits murder shall be punished with death or imprisonment for life, and shall also be liable to fine.",
    source: "Penal Code 1860, Section 302",
    certainty: "confirmed",
    tags: ["murder", "302", "death penalty", "life imprisonment", "homicide"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-culpable-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Culpable Homicide Not Amounting to Murder — Section 304",
    rule: "Punishment for culpable homicide not amounting to murder is imprisonment for life or up to 10 years, and fine. If the act by which death is caused is done with knowledge but without intention, imprisonment up to 10 years or fine or both.",
    source: "Penal Code 1860, Section 304",
    certainty: "confirmed",
    tags: ["culpable homicide", "304", "sudden fight", "provocation", "manslaughter"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-theft-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Theft — Section 379, Penal Code 1860",
    rule: "Whoever commits theft shall be punished with imprisonment of either description for a term which may extend to 3 years, or with fine, or with both.",
    source: "Penal Code 1860, Section 379",
    certainty: "confirmed",
    tags: ["theft", "379", "stealing", "3 years"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-robbery-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Robbery — Section 392, Penal Code 1860",
    rule: "Whoever commits robbery shall be punished with rigorous imprisonment for a term up to 10 years and fine. If robbery is committed on a highway between sunset and sunrise, imprisonment may extend to 14 years.",
    source: "Penal Code 1860, Section 392",
    certainty: "confirmed",
    tags: ["robbery", "392", "10 years", "highway", "violence"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-dacoity-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Dacoity — Section 395, Penal Code 1860",
    rule: "Whoever commits dacoity (robbery by 5 or more persons) shall be punished with imprisonment for life or rigorous imprisonment up to 10 years, and fine.",
    source: "Penal Code 1860, Section 395",
    certainty: "confirmed",
    tags: ["dacoity", "395", "gang robbery", "5 persons", "life imprisonment"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-hurt-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Grievous Hurt — Section 325, Penal Code 1860",
    rule: "Whoever voluntarily causes grievous hurt shall be punished with imprisonment up to 7 years and fine. Grievous hurt includes permanent disfigurement, fracture, or injuries endangering life.",
    source: "Penal Code 1860, Sections 320, 325",
    certainty: "confirmed",
    tags: ["grievous hurt", "325", "7 years", "injury", "disfigurement"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-kidnap-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Kidnapping — Section 363, Penal Code 1860",
    rule: "Whoever kidnaps any person shall be punished with imprisonment up to 7 years and fine. Kidnapping for ransom carries heavier punishment under special laws.",
    source: "Penal Code 1860, Section 363",
    certainty: "confirmed",
    tags: ["kidnapping", "363", "7 years", "abduction"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-forgery-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Forgery — Sections 463-468, Penal Code 1860",
    rule: "Forgery of documents: up to 2 years. Forgery of court records or public registers: up to 7 years. Forgery for purpose of cheating: up to 7 years. Using forged documents: same punishment as forgery.",
    source: "Penal Code 1860, Sections 463-468, 471",
    certainty: "confirmed",
    tags: ["forgery", "463", "468", "fake document", "2-7 years"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-arrest-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Arrest Without Warrant — CrPC Section 54",
    rule: "Police may arrest without warrant in cognizable offences — offences serious enough to allow arrest without court order. These include murder, robbery, dacoity, kidnapping, and most offences punishable with 3 or more years.",
    source: "Code of Criminal Procedure 1898, Section 54",
    certainty: "confirmed",
    tags: ["arrest", "warrant", "section 54", "cognizable", "police power"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-detention-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Maximum Detention Without Court Order — 24 Hours",
    rule: "Under CrPC Section 61, no police officer shall detain in custody a person arrested without warrant for longer than 24 hours. After 24 hours, the arrested person must be produced before a Magistrate.",
    source: "Code of Criminal Procedure 1898, Section 61; Constitution Article 33",
    certainty: "confirmed",
    tags: ["detention", "24 hours", "magistrate", "custody", "police", "section 61"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-bail-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Bailable vs Non-Bailable Offences — CrPC",
    rule: "Bailable offences: bail is a right — police or Magistrate must grant bail. Non-bailable offences: bail is discretionary — court decides based on nature of offence, antecedents, and likelihood of fleeing. High Court has power to grant bail in any case.",
    source: "Code of Criminal Procedure 1898, Sections 496-498; Second Schedule",
    certainty: "confirmed",
    tags: ["bail", "bailable", "non-bailable", "right to bail", "high court bail"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-remand-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Remand — Police Custody for Investigation",
    rule: "Police may apply for remand (custody) for investigation purposes. Magistrate may authorise detention in police custody not exceeding 15 days in total. After 15 days, accused goes to judicial custody (jail), not police station.",
    source: "Code of Criminal Procedure 1898, Section 167",
    certainty: "confirmed",
    tags: ["remand", "police custody", "15 days", "investigation", "magistrate"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-rape-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Rape — Nari O Shishu Nirjatan Daman Ain 2000",
    rule: "Punishment for rape under the Women and Children Repression Prevention Act 2000: rigorous imprisonment for life and fine. If rape causes death, punishment is death or life imprisonment. Gang rape: death or life imprisonment.",
    source: "Nari O Shishu Nirjatan Daman Ain 2000, Section 9",
    certainty: "confirmed",
    tags: ["rape", "women", "children", "nari shishu", "life imprisonment", "section 9"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-acid-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Acid Attack — Nari O Shishu Nirjatan Daman Ain 2000",
    rule: "Punishment for acid attack causing death: death penalty. Causing grievous hurt: death or life imprisonment. Causing simple hurt: imprisonment 3-7 years and fine. Acid Control Act 2002 also regulates acid sale and possession.",
    source: "Nari O Shishu Nirjatan Daman Ain 2000, Section 4; Acid Control Act 2002",
    certainty: "confirmed",
    tags: ["acid attack", "acid", "death penalty", "nari shishu", "acid control"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-drug-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Drug Trafficking — Narcotics Control Act 2018",
    rule: "Punishment for drug trafficking under Narcotics Control Act 2018: death or life imprisonment for trafficking large quantities of heroin, cocaine, or phensidyl. Lesser quantities: 2 years to life depending on drug and amount.",
    source: "Narcotics Control Act 2018, Sections 19, 34",
    certainty: "confirmed",
    tags: ["drug", "narcotics", "trafficking", "heroin", "death penalty", "life imprisonment"],
    lastVerified: "2025-03-09",
  },
  {
    id: "cr-cyber-001",
    area: "criminal",
    jurisdiction: "BD",
    title: "Cyber Defamation — Cyber Security Act 2023",
    rule: "Publishing false defamatory information online: imprisonment up to 3 years or fine up to BDT 5 lakh or both. Hacking/unauthorized access: up to 7 years. Spreading false information to destabilise state: up to 14 years.",
    source: "Cyber Security Act 2023, Sections 21, 17, 28",
    certainty: "confirmed",
    tags: ["cyber", "defamation", "online", "hacking", "cyber security act", "3 years"],
    lastVerified: "2025-03-09",
  },
];

const qaBank: QAEntry[] = [

  // ════════════════════════════════════════════════════════════
  // LAYER 1: CRIME + PUNISHMENT (Penal Code)
  // ════════════════════════════════════════════════════════════

  {
    id: "cr-qa-001",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["punishment murder", "murder punishment", "murder sentence", "section 302", "302 penal code", "হত্যার শাস্তি", "খুনের শাস্তি"],
    question: "What is the punishment for murder in Bangladesh?",
    irac: {
      issue: "What punishment does Bangladesh law prescribe for the offence of murder?",
      rule: "Section 302 of the Penal Code 1860: Whoever commits murder shall be punished with death or imprisonment for life, and shall also be liable to fine.",
      application: "Murder requires: (1) causing death, (2) intention to kill, or knowledge that the act is so imminently dangerous that it will in all probability cause death. Courts consider intention, weapon used, and circumstances to determine whether death penalty or life imprisonment applies.",
      conclusion: "**Murder (Section 302):** Death penalty OR life imprisonment + fine.\n\nCourt decides between the two based on facts. Both are maximum severity sentences.\n\n📋 Law student guide — ৳99 | 📄 Full criminal law notes — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-murder-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-002",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["culpable homicide", "304", "sudden fight death", "unintentional killing", "not murder", "আকস্মিক মারামারি মৃত্যু"],
    question: "What is the difference between murder and culpable homicide?",
    irac: {
      issue: "How does Bangladesh law distinguish murder (Section 302) from culpable homicide not amounting to murder (Section 304)?",
      rule: "Penal Code 1860: Murder (S.302) = intentional killing with premeditation. Culpable Homicide (S.304) = causing death without full murder intention — in sudden fight, under grave provocation, or with knowledge (not intention) that death may result.",
      application: "Classic distinction: A plans to kill B and stabs him → Murder (S.302). A and B fight, A hits B impulsively and B dies → Culpable Homicide (S.304). The key difference is premeditation and intention. Sudden provocation reduces murder to culpable homicide.",
      conclusion: "**Murder (S.302):** Death or life imprisonment.\n**Culpable Homicide (S.304 Part I):** Life imprisonment or up to 10 years.\n**Culpable Homicide (S.304 Part II — knowledge, no intention):** Up to 10 years or fine.\n\n📋 Exam notes — ৳99 | 📄 Case law guide — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-murder-001", "cr-culpable-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-003",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["theft punishment", "section 379", "চুরির শাস্তি", "theft sentence"],
    question: "What is the punishment for theft in Bangladesh?",
    irac: {
      issue: "What punishment does the Penal Code prescribe for theft?",
      rule: "Section 379, Penal Code 1860: Whoever commits theft shall be punished with imprisonment up to 3 years, or fine, or both. Theft in dwelling house (S.380): up to 7 years. Theft by clerk or servant (S.381): up to 7 years.",
      application: "Theft = dishonestly moving another's property without consent. Simple theft: 3 years max. If theft is from someone's home, or by a trusted employee, the punishment increases.",
      conclusion: "**Simple Theft (S.379):** Up to 3 years or fine or both.\n**Theft in dwelling (S.380):** Up to 7 years.\n**Theft by servant (S.381):** Up to 7 years.\n\n📋 Penal Code summary — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-theft-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-004",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["robbery", "section 392", "ছিনতাই", "robbery punishment", "ডাকাতি আইন"],
    question: "What is robbery and what is the punishment?",
    irac: {
      issue: "How does Bangladesh law define robbery and what punishment applies?",
      rule: "Section 390, Penal Code 1860: Robbery = theft + violence or threat of violence. OR extortion + immediate fear of death or grievous hurt. Section 392: Punishment up to 10 years rigorous imprisonment and fine. Highway robbery at night: up to 14 years.",
      application: "Robbery requires theft combined with force or threat. Snatching a phone while threatening the victim = robbery. Simple pickpocketing without threat = theft only.",
      conclusion: "**Robbery (S.392):** Up to 10 years rigorous imprisonment + fine.\n**Highway robbery (night):** Up to 14 years.\n**Robbery with attempt to cause death/grievous hurt (S.394):** Life imprisonment or up to 10 years.\n\n📋 Criminal law notes — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-robbery-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-005",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["dacoity", "section 395", "gang robbery", "ডাকাতি", "dacoity punishment"],
    question: "What is dacoity and what is the punishment?",
    irac: {
      issue: "What constitutes dacoity under Bangladesh law and what punishment applies?",
      rule: "Section 391, Penal Code 1860: Dacoity = robbery committed by 5 or more persons conjointly. Section 395: Punishment — life imprisonment or rigorous imprisonment up to 10 years and fine. Dacoity with murder (S.396): Death or life imprisonment.",
      application: "5 or more persons acting together to commit robbery = dacoity. Even if not all 5 physically commit the robbery — if they act together in a common intention, all are guilty of dacoity.",
      conclusion: "**Dacoity (S.395):** Life imprisonment OR up to 10 years + fine.\n**Dacoity with murder (S.396):** Death OR life imprisonment.\n\n📋 Criminal law exam guide — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-dacoity-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-006",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["grievous hurt", "section 325", "গুরুতর জখম", "serious injury punishment"],
    question: "What is grievous hurt and what is the punishment?",
    irac: {
      issue: "How does Bangladesh law define grievous hurt and what punishment applies?",
      rule: "Section 320, Penal Code 1860: Grievous hurt includes — emasculation, permanent loss of sight/hearing, loss of any member or joint, permanent disfigurement, fracture, or any hurt endangering life or causing 20-day severe bodily pain. Section 325: Punishment up to 7 years and fine.",
      application: "Breaking someone's bone = grievous hurt (fracture). Disfiguring someone's face permanently = grievous hurt. Simple bruising = simple hurt (S.323, up to 1 year only).",
      conclusion: "**Grievous Hurt (S.325):** Up to 7 years + fine.\n**Simple Hurt (S.323):** Up to 1 year or fine.\n**Hurt by dangerous weapon (S.326):** Life imprisonment or up to 10 years.\n\n📋 Penal Code notes — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-hurt-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-007",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["kidnapping", "section 363", "অপহরণ শাস্তি", "kidnapping punishment", "abduction"],
    question: "What is the punishment for kidnapping in Bangladesh?",
    irac: {
      issue: "What punishment does Bangladesh law prescribe for kidnapping and abduction?",
      rule: "Section 363, Penal Code 1860: Kidnapping from Bangladesh or from lawful guardianship — up to 7 years imprisonment and fine. Kidnapping for ransom (S.364A): Death or life imprisonment. Kidnapping to murder (S.364): Life imprisonment or up to 10 years.",
      application: "Simple kidnapping of an adult = 7 years. Kidnapping a child from guardian = 7 years. Kidnapping for ransom money = death or life imprisonment — far more serious.",
      conclusion: "**Simple Kidnapping (S.363):** Up to 7 years + fine.\n**Kidnapping for ransom (S.364A):** Death or life imprisonment.\n**Kidnapping to murder (S.364):** Life imprisonment or up to 10 years.\n\n📋 Criminal law guide — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-kidnap-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-008",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["forgery", "section 463", "জাল দলিল শাস্তি", "forgery punishment", "fake document crime"],
    question: "What is the punishment for forgery in Bangladesh?",
    irac: {
      issue: "What punishment does Bangladesh law prescribe for making or using forged documents?",
      rule: "Penal Code 1860: Forgery (S.463-465): up to 2 years or fine or both. Forgery of court record, register, or public document (S.466-467): up to 7 years. Forgery for cheating (S.468): up to 7 years. Using forged document as genuine (S.471): same as forgery itself.",
      application: "Making a fake rent receipt = 2 years. Forging a land deed (public document) = 7 years. Using a known forged deed in court = 7 years. Both maker and user of forged documents face punishment.",
      conclusion: "**Simple Forgery (S.465):** Up to 2 years or fine.\n**Forgery of public/court document (S.467):** Up to 7 years.\n**Forgery for cheating (S.468):** Up to 7 years.\n**Using forged document (S.471):** Equal to the forgery committed.\n\n📋 Criminal law notes — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-forgery-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-009",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["cheating", "section 415", "প্রতারণা শাস্তি", "fraud penal code", "cheating punishment"],
    question: "What is cheating under criminal law and what is the punishment?",
    irac: {
      issue: "How does Bangladesh criminal law define cheating and what punishment applies?",
      rule: "Section 415, Penal Code 1860: Cheating = deceiving a person fraudulently to deliver property, or to do or omit something causing damage. Section 417: Simple cheating — up to 1 year or fine. Section 420: Cheating and dishonestly inducing delivery of property — up to 7 years and fine.",
      application: "Selling fake medicine = cheating (S.420). Taking money promising services and disappearing = cheating. The key element is deception causing the victim to act to their own detriment.",
      conclusion: "**Simple Cheating (S.417):** Up to 1 year or fine.\n**Cheating by inducing delivery (S.420):** Up to 7 years + fine.\n\n📋 Penal Code summary — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-010",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["criminal breach of trust", "section 405", "আমানতের খেয়ানত", "misappropriation punishment"],
    question: "What is criminal breach of trust and what is the punishment?",
    irac: {
      issue: "What constitutes criminal breach of trust under Bangladesh law?",
      rule: "Section 405, Penal Code 1860: Criminal breach of trust = dishonest misappropriation or conversion of property entrusted to someone. Section 406: Punishment up to 3 years or fine or both. By carrier, warehouse keeper, or agent (S.407-408): up to 7 years.",
      application: "A company employee uses company money for personal expenses = criminal breach of trust. A lawyer misuses client funds held in trust = criminal breach of trust by agent (7 years).",
      conclusion: "**Criminal Breach of Trust (S.406):** Up to 3 years or fine.\n**By clerk/agent (S.408):** Up to 7 years + fine.\n**By public servant (S.409):** Life imprisonment or up to 10 years.\n\n📋 Criminal law guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-011",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["criminal intimidation", "section 503", "ভয় দেখানো", "threat punishment", "threatening"],
    question: "What is criminal intimidation and what is the punishment?",
    irac: {
      issue: "What constitutes criminal intimidation under the Penal Code and what punishment applies?",
      rule: "Section 503, Penal Code 1860: Criminal intimidation = threatening a person with injury to themselves, their reputation, or property, intending to cause alarm or compel them to act. Section 506: Punishment up to 2 years or fine or both. If threat is to cause death or grievous hurt: up to 7 years.",
      application: "Threatening to harm someone if they testify in court = criminal intimidation. Sending threatening messages = criminal intimidation. Both verbal and written threats qualify.",
      conclusion: "**Criminal Intimidation (S.506 Part I):** Up to 2 years or fine.\n**Threat of death or grievous hurt (S.506 Part II):** Up to 7 years or fine.\n\n📋 Penal Code notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-012",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["defamation penal code", "section 499", "মানহানি", "defamation criminal", "criminal defamation"],
    question: "What is defamation under criminal law and what is the punishment?",
    irac: {
      issue: "What constitutes criminal defamation under the Penal Code?",
      rule: "Section 499, Penal Code 1860: Defamation = making or publishing any imputation concerning a person intending to harm their reputation. Section 500: Punishment up to 2 years or fine or both. Publishing defamatory matter (S.501): up to 2 years. Selling defamatory publication (S.502): up to 2 years.",
      application: "Falsely accusing someone of theft in public = defamation. Truth is a complete defence if published for public good. Fair comment on public figures on matters of public interest is not defamation.",
      conclusion: "**Criminal Defamation (S.500):** Up to 2 years or fine.\n\nTruth for public good = complete defence.\nFair comment = defence.\n\nNote: Online defamation falls under Cyber Security Act 2023 (up to 3 years).\n\n📋 Criminal law notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  // ════════════════════════════════════════════════════════════
  // LAYER 2: PROCEDURE (CrPC) — CITIZEN QUESTIONS
  // ════════════════════════════════════════════════════════════

  {
    id: "cr-qa-013",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["how to file fir", "file criminal case", "file case police", "মামলা দায়ের", "থানায় মামলা", "how to complain police"],
    question: "How do I file a criminal case (FIR) in Bangladesh?",
    irac: {
      issue: "What is the process for filing a First Information Report (FIR) at a police station in Bangladesh?",
      rule: "Under CrPC Section 154, any person can report a cognizable offence to the police. The Officer-in-Charge must record it as FIR and give a copy free of charge. If police refuse, the complainant can file a complaint directly to the Magistrate under Section 200.",
      application: "Go to the police station where the offence occurred. State the facts clearly. Police must register FIR for cognizable offences — they cannot refuse. Get the FIR number and a copy. If refused, go to Magistrate Court directly.",
      conclusion: "**Steps:**\n1. Go to nearest Police Station (where offence occurred)\n2. State facts to Officer-in-Charge\n3. FIR is written and signed by you\n4. Demand free copy of FIR — your right\n5. If police refuse → file complaint at Magistrate Court (S.200)\n6. If Magistrate ignored → complain to SP or High Court\n\n📋 FIR document guide — ৳99 | 📄 Full procedure pack — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-arrest-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-014",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["what is fir", "fir meaning", "first information report", "এফআইআর কি", "fir bangladesh"],
    question: "What is an FIR (First Information Report)?",
    irac: {
      issue: "What is an FIR and what legal significance does it have in Bangladesh criminal law?",
      rule: "FIR (First Information Report) under CrPC Section 154 is the first information given to police about a cognizable offence. It sets the investigation in motion. The FIR is a document of great evidentiary value — courts rely on it to assess consistency of the complainant's version.",
      application: "FIR is only for cognizable offences (serious crimes — murder, robbery, rape, kidnapping etc.). For non-cognizable offences (minor matters), a written complaint is taken but no FIR — police need Magistrate's permission to investigate.",
      conclusion: "**FIR = First formal report of a serious crime to police.**\n\nCognizable offence → FIR → police investigate without Magistrate order.\nNon-cognizable offence → written complaint → Magistrate permission needed to investigate.\n\nAlways keep a copy of your FIR.\n\n📋 Criminal procedure notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-015",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["police arrest without warrant", "arrested without warrant", "can police arrest me", "ওয়ারেন্ট ছাড়া গ্রেফতার", "section 54"],
    question: "Can police arrest me without a warrant?",
    irac: {
      issue: "Under what circumstances can Bangladesh police arrest a person without a court warrant?",
      rule: "CrPC Section 54: Police may arrest without warrant any person who has committed or is suspected of committing a cognizable offence, any proclaimed offender, any person found with suspicious tools, or anyone obstructing a police officer in duty.",
      application: "Cognizable offences include murder, robbery, rape, kidnapping, drug trafficking, and most offences punishable with 3+ years. For non-cognizable offences (minor matters), police need a warrant from a Magistrate before arresting.",
      conclusion: "**Police CAN arrest without warrant for cognizable offences.**\n\nYour rights on arrest:\n• Must be told reason for arrest\n• Right to inform family or friend\n• Must be produced before Magistrate within 24 hours\n• Right to engage a lawyer\n• Right to remain silent\n\n📋 Rights on arrest — ৳99 | 📄 Full guide — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-arrest-001", "cr-detention-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-016",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["how long detained", "police detention time", "24 hours police", "কতক্ষণ আটকে রাখতে পারে", "detention limit"],
    question: "How long can police detain me without a court order?",
    irac: {
      issue: "What is the maximum time police can hold a person after arrest before producing them before a court?",
      rule: "CrPC Section 61 and Constitution Article 33(2): No police officer shall detain an arrested person for more than 24 hours without producing them before the nearest Magistrate. The 24 hours includes travel time.",
      application: "If arrested at 10am on Monday, you must be produced before a Magistrate by 10am Tuesday at the latest. If not, the detention becomes illegal. You or your family can file a Habeas Corpus writ in High Court to secure release.",
      conclusion: "**Maximum 24 hours police detention without court order.**\n\nAfter 24 hours: must appear before Magistrate.\nMagistrate can then authorize remand (police custody) for investigation — maximum 15 days total.\nAfter 15 days: must go to jail custody (not police station).\n\n⚠️ If detained beyond 24 hours without Magistrate — file Habeas Corpus at High Court immediately.\n\n📋 Detention rights guide — ৳99",
    },
    escalate: true,
    escalateReason: "Illegal detention beyond 24 hours requires urgent High Court writ. WhatsApp NLC immediately.",
    relatedRules: ["cr-detention-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-017",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["what is remand", "remand meaning", "রিমান্ড কি", "police remand", "remand bangladesh"],
    question: "What is remand and what are my rights during remand?",
    irac: {
      issue: "What is remand in Bangladesh criminal procedure and what rights does an accused have?",
      rule: "CrPC Section 167: When police cannot complete investigation within 24 hours, they produce the accused before a Magistrate and apply for remand — custody for further investigation. Magistrate can grant police custody up to 15 days in total. After 15 days, only jail custody is allowed, not police station.",
      application: "During remand, police question the accused. The accused has the right to have a lawyer present. Physical torture during remand is illegal under the Torture and Custodial Death (Prevention) Act 2013. If tortured, file complaint with Human Rights Commission and Magistrate.",
      conclusion: "**Remand = police custody for investigation, authorised by Magistrate.**\n\nMaximum 15 days total police custody.\nYour rights during remand:\n• Right to lawyer\n• Right against torture — Torture Act 2013\n• Magistrate must visit jail periodically\n• Family can be informed\n\n⚠️ Torture during remand is a criminal offence — offending officer can be prosecuted.\n\n📋 Remand rights guide — ৳99 | 📄 Full procedure — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-remand-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-018",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["how to get bail", "bail application", "জামিন পাবো কিভাবে", "bail procedure", "apply for bail"],
    question: "How do I get bail after arrest?",
    irac: {
      issue: "What is the process for obtaining bail after arrest in Bangladesh?",
      rule: "CrPC Sections 496-498: Bailable offences — bail is a right, police station bail or Magistrate bail. Non-bailable offences — bail at discretion of Sessions Court or High Court. High Court has inherent power to grant bail in any case under Section 498.",
      application: "For bailable offence: apply at police station itself or before Magistrate — bail must be granted. For non-bailable offence: appear before Sessions Judge with bail application stating grounds (illness, family situation, no flight risk, clean record). If Sessions Court refuses, apply to High Court.",
      conclusion: "**Bailable offence:** Apply at police station or Magistrate — bail is your right.\n**Non-bailable offence:** Apply to Sessions Judge → if refused → High Court.\n\nBail application should include:\n• Nature of offence\n• Personal circumstances\n• Sureties (guarantors)\n• No flight risk argument\n• No tampering with evidence argument\n\n📋 Bail application template — ৳199 | 📄 Full bail guide — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-bail-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-019",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["anticipatory bail", "pre arrest bail", "আগাম জামিন", "false case bail", "anticipatory bail bangladesh"],
    question: "What is anticipatory bail and how do I apply?",
    irac: {
      issue: "What is anticipatory bail and when can it be obtained in Bangladesh?",
      rule: "CrPC Section 498 gives the High Court Division inherent power to grant bail to any person fearing arrest. Though not explicitly called 'anticipatory bail' in Bangladesh CrPC (unlike India), the High Court regularly grants pre-arrest bail on application, citing Section 498 and Article 44 of the Constitution.",
      application: "If you fear arrest in a false or malicious case, apply to High Court Division with: details of the case, why it is false, your background, and why you should not be arrested. Court may grant a stay of arrest or interim bail pending hearing.",
      conclusion: "**Anticipatory Bail in Bangladesh:**\nApply to High Court Division under CrPC S.498 + Constitution Article 44.\n\nRequired:\n• Affidavit explaining fear of arrest\n• Why case is false or malicious\n• Your clean background\n• Undertaking to cooperate with investigation\n\n⚠️ Must engage advocate for High Court application.\n\n📄 Full anticipatory bail guide — ৳1,999",
    },
    escalate: true,
    escalateReason: "High Court bail application requires qualified advocate. WhatsApp NLC for referral.",
    relatedRules: ["cr-bail-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-020",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["police refuse fir", "police not taking case", "police refuse complaint", "পুলিশ মামলা নিচ্ছে না", "fir refused"],
    question: "What do I do if police refuse to file my FIR?",
    irac: {
      issue: "What legal remedy exists when police refuse to register an FIR for a cognizable offence?",
      rule: "CrPC Section 154(3): If Officer-in-Charge refuses to record FIR, the complainant can send the complaint by post to the Superintendent of Police (SP). CrPC Section 200: The complainant can also file a complaint directly before a Magistrate. The Magistrate can take cognizance and direct police to investigate.",
      application: "Police refusing FIR is itself an offence of dereliction of duty. Complainant has three remedies: (1) Write to SP, (2) File at Magistrate Court, (3) File writ in High Court for direction to police.",
      conclusion: "**If police refuse FIR:**\n1. Write complaint to Superintendent of Police (SP) — send by registered post + keep copy\n2. File complaint directly at Magistrate Court (Chief Judicial Magistrate)\n3. If Magistrate also fails — file writ in High Court Division\n\n📋 Complaint letter template — ৳99 | 📄 Full procedure guide — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-021",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["charge sheet", "what is charge sheet", "চার্জশিট কি", "police report court", "final report police"],
    question: "What is a charge sheet and what happens after it is filed?",
    irac: {
      issue: "What is a charge sheet in Bangladesh criminal procedure and what happens after it is submitted?",
      rule: "CrPC Section 173: After completing investigation, police must submit a report to the Magistrate — called the charge sheet (if evidence found) or final report (if no evidence). Charge sheet contains: offence, accused names, witnesses, evidence summary.",
      application: "Charge sheet is submitted: court takes cognizance → frames charges → trial begins. If final report (no evidence): Magistrate can accept and close case, or reject and direct further investigation. Complainant can file naraji petition if dissatisfied with final report.",
      conclusion: "**After charge sheet:**\n1. Court takes cognizance of offence\n2. Accused summoned/arrested\n3. Charges formally framed\n4. Trial begins — prosecution examines witnesses\n5. Defence cross-examines\n6. Arguments → Judgment\n\nIf no charge sheet (final report) and you disagree → file Naraji Petition at Magistrate Court.\n\n📋 Naraji petition guide — ৳199 | 📄 Full trial procedure — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-022",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["criminal trial stages", "trial procedure", "criminal case procedure", "বিচার প্রক্রিয়া", "how court trial works"],
    question: "What are the stages of a criminal trial in Bangladesh?",
    irac: {
      issue: "What is the step-by-step process of a criminal trial in Bangladesh courts?",
      rule: "CrPC 1898 lays out the trial stages: Charge → Plea → Prosecution evidence → Defence evidence → Arguments → Judgment → Sentence (if convicted) → Appeal.",
      application: "After charge sheet, the court frames charges and reads them to the accused. Accused pleads guilty or not guilty. Prosecution examines its witnesses. Defence cross-examines. Defence then presents its witnesses. Final arguments. Judge delivers judgment. If convicted, sentence is pronounced.",
      conclusion: "**Bangladesh Criminal Trial Stages:**\n1. Cognizance by court\n2. Framing of charges\n3. Accused plea (guilty/not guilty)\n4. Prosecution evidence (PW)\n5. Defence cross-examination\n6. Section 342 examination of accused\n7. Defence evidence (DW)\n8. Final arguments\n9. Judgment\n10. Sentence (if guilty)\n11. Appeal (if desired)\n\n📋 Trial stages notes — ৳99 | 📄 Full criminal procedure — ৳1,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-023",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["appeal criminal case", "criminal appeal", "দণ্ডের বিরুদ্ধে আপিল", "challenge conviction", "how to appeal"],
    question: "How do I appeal against a criminal conviction?",
    irac: {
      issue: "What is the process for appealing a criminal conviction in Bangladesh?",
      rule: "CrPC Sections 408-431: Appeals from Magistrate Court go to Sessions Court. Appeals from Sessions Court go to High Court Division. Appeals from High Court go to Appellate Division (Supreme Court). The accused can also file a revision petition in High Court challenging wrong application of law.",
      application: "After conviction, the accused has a right to appeal to the next higher court. The appeal must be filed within limitation period — usually 30 days from judgment date. In death penalty cases, the case must be confirmed by High Court Division (death reference).",
      conclusion: "**Criminal Appeal Path:**\n• Magistrate Court conviction → Sessions Court appeal\n• Sessions Court conviction → High Court Division\n• High Court conviction → Appellate Division (Supreme Court)\n• Death sentence → automatically sent to High Court for confirmation\n\nTime limit: Generally 30 days from judgment.\n\n⚠️ Engage advocate immediately for appeal — time limit is strict.\n\n📄 Appeal procedure guide — ৳1,999",
    },
    escalate: true,
    escalateReason: "Criminal appeal has strict 30-day time limit. WhatsApp NLC for urgent referral.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-024",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["can case be withdrawn", "case withdrawal", "মামলা প্রত্যাহার", "criminal case compromise", "settle criminal case"],
    question: "Can a criminal case be withdrawn or compromised?",
    irac: {
      issue: "Under what circumstances can a criminal case be withdrawn or settled by compromise in Bangladesh?",
      rule: "CrPC Section 494: A Public Prosecutor can withdraw a case with Magistrate's permission at any stage before judgment. CrPC Section 345: Certain offences are compoundable — parties can reach compromise to close the case. List of compoundable offences is in Section 345.",
      application: "Compoundable offences include: assault, cheating, defamation, criminal breach of trust. Murder, robbery, rape, dacoity — NOT compoundable. For compoundable offences, victim and accused agree → court accepts compromise → case closed. Government cases (state as complainant) need government permission to withdraw.",
      conclusion: "**Compoundable offences:** Parties can settle — case closed by court.\n**Non-compoundable offences (murder, rape etc.):** Cannot be compromised by parties — only government can withdraw.\n\nCommon compoundable offences:\n• Assault (S.323) ✓\n• Cheating (S.417) ✓\n• Criminal breach of trust (S.406) ✓\n• Defamation (S.500) ✓\n\n📋 Compounding procedure — ৳199 | 📄 Full guide — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-025",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["rights of accused", "accused rights", "আসামির অধিকার", "rights after arrest", "what rights arrested"],
    question: "What are the rights of an accused person in Bangladesh?",
    irac: {
      issue: "What fundamental and procedural rights does an accused person have under Bangladesh law?",
      rule: "Constitution Articles 31-35 + CrPC: Right to know reason for arrest, right to lawyer, right to remain silent, right to be produced before Magistrate within 24 hours, right against self-incrimination, right against double jeopardy, right to fair trial.",
      application: "These rights apply from the moment of arrest. Police cannot force confession. Evidence obtained by torture is inadmissible. The accused is presumed innocent until proven guilty.",
      conclusion: "**Rights of Accused — Bangladesh:**\n1. Know reason for arrest (Constitution Art.33)\n2. Inform family/friend immediately\n3. Right to engage lawyer of choice\n4. Right to remain silent — no forced confession\n5. Produced before Magistrate within 24 hours\n6. Right against torture (Torture Act 2013)\n7. Right against self-incrimination (Art.35)\n8. Right against double jeopardy (tried twice for same offence)\n9. Presumed innocent until proven guilty\n10. Right to fair, public trial\n\n📋 Rights of accused guide — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-detention-001", "cr-bail-001"],
    lastVerified: "2025-03-09",
  },

  // ════════════════════════════════════════════════════════════
  // LAYER 3: SPECIAL CRIMINAL LAWS
  // ════════════════════════════════════════════════════════════

  {
    id: "cr-qa-026",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["rape punishment", "punishment rape", "ধর্ষণ শাস্তি", "rape sentence bangladesh", "nari shishu rape"],
    question: "What is the punishment for rape under Bangladesh law?",
    irac: {
      issue: "What punishment does Bangladesh law prescribe for rape?",
      rule: "Nari O Shishu Nirjatan Daman Ain 2000 (amended 2020), Section 9: Rape causing death or resulting in persistent vegetative state — death penalty. Rape (without death) — life imprisonment (rigorous). Gang rape causing death — death penalty or life imprisonment for all participants.",
      application: "The 2020 amendment removed the maximum 14-year punishment option and made all rape punishable with death or life imprisonment. Rape of a child (under 16) carries the same punishment. Marital rape is not specifically recognised as a separate offence under current Bangladesh law.",
      conclusion: "**Rape (S.9, Nari O Shishu Ain 2000 as amended 2020):**\n• Rape + death of victim → Death penalty\n• Rape (without death) → Life imprisonment (rigorous)\n• Gang rape + death → Death penalty for all\n• Gang rape (without death) → Life imprisonment for all\n\n⚠️ Victim should file case immediately — medical evidence (within 72 hours) is critical.\n\n📋 Victim reporting guide — ৳99 | 📄 Full procedure — ৳999",
    },
    escalate: true,
    escalateReason: "Rape cases require immediate police report and medical examination. Contact NLC for referral to specialist advocate.",
    relatedRules: ["cr-rape-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-027",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["acid attack punishment", "acid crime", "অ্যাসিড নিক্ষেপ শাস্তি", "acid attack bangladesh"],
    question: "What is the punishment for acid attack in Bangladesh?",
    irac: {
      issue: "What punishment does Bangladesh law prescribe for acid attacks?",
      rule: "Nari O Shishu Nirjatan Daman Ain 2000, Section 4: Acid attack causing death — death penalty. Causing permanent grievous hurt (loss of sight/limb/disfigurement) — death or life imprisonment. Causing simple hurt — rigorous imprisonment 3 to 7 years. Acid Control Act 2002 regulates acid sale and possession.",
      application: "Acid throwing is treated with extreme severity in Bangladesh due to widespread misuse. Possession of acid without licence is also an offence. Sellers must maintain buyer records.",
      conclusion: "**Acid Attack Punishment:**\n• Death of victim → Death penalty\n• Permanent disfigurement/blindness → Death or life imprisonment\n• Simple injury → 3–7 years rigorous imprisonment\n\nAcid Control Act 2002: Unlicensed acid possession → up to 3 years.\n\n📋 Victim reporting guide — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-acid-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-028",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["drug trafficking punishment", "narcotics", "মাদক শাস্তি", "drug crime bangladesh", "narcotics act 2018"],
    question: "What is the punishment for drug trafficking in Bangladesh?",
    irac: {
      issue: "What punishment does the Narcotics Control Act 2018 prescribe for drug trafficking?",
      rule: "Narcotics Control Act 2018: Trafficking heroin (above 25 grams), cocaine, phensidyl (above 2500ml), or cannabis (above 25 kg) — death penalty or life imprisonment. Lesser quantities — 2 years to life depending on drug type and amount. Simple possession for personal use — minimum 6 months.",
      application: "Bangladesh has severe drug laws. Even carrying a small quantity can lead to years of imprisonment. Drug cases are tried in Speedy Trial Tribunals and Narcotics Control Courts.",
      conclusion: "**Drug Trafficking (Narcotics Control Act 2018):**\n• Large quantity heroin/cocaine → Death or life imprisonment\n• Medium quantity → 5–15 years\n• Small quantity possession → 6 months – 5 years\n• Drug financing → 3–10 years\n\n⚠️ Engage advocate immediately — drug cases move fast in Bangladesh courts.\n\n📄 Drug case procedure guide — ৳1,999",
    },
    escalate: true,
    escalateReason: "Drug cases carry severe penalties. WhatsApp NLC for immediate referral.",
    relatedRules: ["cr-drug-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-029",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["cyber crime punishment", "digital security act", "সাইবার অপরাধ", "online crime bangladesh", "cyber security act 2023"],
    question: "What are the punishments under the Cyber Security Act 2023?",
    irac: {
      issue: "What offences and punishments does the Cyber Security Act 2023 of Bangladesh establish?",
      rule: "Cyber Security Act 2023 (replacing Digital Security Act 2018): Section 17 — hacking/unauthorized access: up to 7 years or BDT 10 lakh fine. Section 21 — defamation online: up to 3 years or BDT 5 lakh. Section 25 — spreading offensive/false information: up to 3 years. Section 28 — religious sentiment: up to 5 years. Section 31 — destabilising state/spreading confusion: up to 14 years.",
      application: "The Act is widely used in Bangladesh. Section 25 and 31 are frequently applied to journalists and critics. Online defamation carries both criminal punishment and heavy fine. Cases are tried in Cyber Tribunal.",
      conclusion: "**Key Cyber Security Act 2023 Offences:**\n• Hacking/unauthorized access (S.17) → Up to 7 years\n• Online defamation (S.21) → Up to 3 years\n• False/offensive information (S.25) → Up to 3 years\n• Religious sentiment (S.28) → Up to 5 years\n• State destabilisation (S.31) → Up to 14 years\n\nCases tried at: Cyber Tribunal\n\n📋 Cyber crime reporting guide — ৳99 | 📄 Full guide — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-cyber-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-030",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["human trafficking", "trafficking punishment", "মানব পাচার শাস্তি", "trafficking bangladesh"],
    question: "What is the punishment for human trafficking in Bangladesh?",
    irac: {
      issue: "What punishment does Bangladesh law prescribe for human trafficking?",
      rule: "Human Trafficking Deterrence and Suppression Act 2012: Trafficking a person — death penalty or life imprisonment and fine. Trafficking a child — death penalty or life imprisonment. Facilitating trafficking — up to 20 years. Trafficking for organ removal — up to 20 years or death.",
      application: "Human trafficking includes luring people with false job offers abroad, forced prostitution, and child trafficking. Bangladesh is a source, transit, and destination country for trafficking. Cases are tried in special Human Trafficking Tribunals.",
      conclusion: "**Human Trafficking Act 2012:**\n• Adult trafficking → Death or life imprisonment\n• Child trafficking → Death or life imprisonment\n• Facilitating → Up to 20 years\n• Organ trafficking → Up to 20 years or death\n\n📋 Victim reporting guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-031",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["torture custody", "custodial torture", "police torture", "হেফাজতে নির্যাতন", "torture act"],
    question: "What is the law against police torture in Bangladesh?",
    irac: {
      issue: "What legal protection exists against torture by police or other law enforcement in Bangladesh?",
      rule: "Torture and Custodial Death (Prevention) Act 2013: Any police officer or public official who tortures a person in custody commits an offence punishable with up to 5 years imprisonment and fine. Custodial death due to torture — punishable with death or life imprisonment.",
      application: "If you or a family member is tortured in police custody: file complaint with Magistrate, Human Rights Commission, and police headquarters. The accused officer can be prosecuted. A Magistrate must conduct inquest in cases of custodial death.",
      conclusion: "**Torture in custody is a criminal offence:**\n• Torture by official → Up to 5 years + fine\n• Custodial death from torture → Death or life imprisonment\n\n**If you face torture:**\n1. Inform Magistrate on next court appearance\n2. File complaint with National Human Rights Commission\n3. Write to Inspector General of Police\n4. Engage advocate immediately\n\n📄 Custodial torture complaint guide — ৳999",
    },
    escalate: true,
    escalateReason: "Custodial torture cases are urgent. WhatsApp NLC for immediate referral.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  // ════════════════════════════════════════════════════════════
  // LAYER 4: CASE SCENARIOS (Student + Citizen)
  // ════════════════════════════════════════════════════════════

  {
    id: "cr-qa-032",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["knife fight death", "fight death", "murder or culpable homicide", "মারামারিতে মৃত্যু", "which offence fight death"],
    question: "A fight breaks out and someone dies — is it murder or culpable homicide?",
    irac: {
      issue: "How do courts determine whether a death in a fight constitutes murder (S.302) or culpable homicide (S.304)?",
      rule: "Penal Code 1860: The key distinction is intention and premeditation. Murder (S.302) requires intention to kill or knowledge that the act will definitely cause death. Culpable homicide (S.304) applies when death results from a sudden fight, grave provocation, or without clear intention to kill.",
      application: "Scenario A: A pre-plans to kill B, meets him and stabs → Murder (S.302) — premeditation + intention. Scenario B: A and B argue, fight breaks out suddenly, A hits B impulsively and B dies → Culpable Homicide (S.304) — sudden provocation, no premeditation. Scenario C: A and B fight, A hits B knowing his weak heart might not survive → S.304 Part II (knowledge without intention).",
      conclusion: "**Fight → Death scenarios:**\n\n✦ Pre-planned, deliberate killing → **Murder (S.302)** → Death or life imprisonment\n✦ Sudden fight, sudden blow → **Culpable Homicide Part I (S.304)** → Life imprisonment or up to 10 years\n✦ Blow with knowledge (not intention) → **Culpable Homicide Part II (S.304)** → Up to 10 years or fine\n\nIntention = Murder. Sudden provocation = Culpable Homicide.\n\n📋 Criminal law exam notes — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-murder-001", "cr-culpable-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-033",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["theft robbery scenario", "snatching phone crime", "purse snatched", "phone snatched", "ছিনতাই মামলা"],
    question: "Someone snatched my phone — is it theft or robbery?",
    irac: {
      issue: "How does Bangladesh law classify a phone snatching incident — as theft or robbery?",
      rule: "Penal Code 1860: Theft (S.378) = taking property without force or threat. Robbery (S.390) = theft + violence OR threat of violence used immediately before, during, or after taking. The presence or absence of force or threat is the determining factor.",
      application: "Scenario A: Pickpocket quietly removes phone from pocket without person noticing → Theft (S.379, up to 3 years). Scenario B: Person grabs phone from hand while running away → arguably theft or robbery depending on whether force was used. Scenario C: Person threatens victim and takes phone → Robbery (S.392, up to 10 years).",
      conclusion: "**Phone snatching scenarios:**\n\n✦ Quiet pickpocketing → **Theft (S.379)** → Up to 3 years\n✦ Snatching from hand (sudden grab) → **Theft or Robbery** — fact-dependent\n✦ Threatening + taking → **Robbery (S.392)** → Up to 10 years\n✦ Group snatching (5+) → **Dacoity (S.395)** → Life imprisonment\n\n📋 Criminal law notes — ৳99",
    },
    escalate: false,
    relatedRules: ["cr-theft-001", "cr-robbery-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-034",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["false case against me", "false criminal case", "মিথ্যা মামলা", "fabricated case", "framed by police"],
    question: "A false criminal case has been filed against me — what do I do?",
    irac: {
      issue: "What legal remedies exist for a person who has been falsely accused in a criminal case in Bangladesh?",
      rule: "CrPC + Constitution: A falsely accused person can apply for bail, challenge the FIR, apply for anticipatory bail before arrest, file writ in High Court challenging illegal investigation, and ultimately seek acquittal at trial. Filing a false FIR is itself an offence under Penal Code S.182 (up to 6 months).",
      application: "Do not ignore summons or run — it makes matters worse. Engage advocate immediately. Gather evidence of your innocence — alibi, witnesses, documents. If arrested, apply for bail. If investigation is clearly malicious, file writ in High Court. At trial — cross-examine prosecution witnesses vigorously.",
      conclusion: "**If falsely accused:**\n1. Do NOT ignore summons — appear in court\n2. Engage advocate immediately\n3. Apply for bail (bailable: right; non-bailable: Sessions Court)\n4. If fearing arrest → apply for anticipatory bail at High Court\n5. Gather alibi, witnesses, documents\n6. Challenge the FIR at High Court if malicious\n7. At trial — prosecution must prove beyond reasonable doubt\n8. After acquittal → file case against false complainant (S.182 Penal Code + malicious prosecution)\n\n⚠️ WhatsApp NLC for immediate referral to criminal advocate.\n\n📄 False case defence guide — ৳1,999",
    },
    escalate: true,
    escalateReason: "False criminal case requires urgent legal action. WhatsApp NLC immediately.",
    relatedRules: ["cr-bail-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-035",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["wife beaten husband", "domestic violence", "স্বামী মারধর", "husband beating wife", "domestic abuse"],
    question: "My husband beats me — what can I do under criminal law?",
    irac: {
      issue: "What criminal remedies does a woman have against domestic violence by her husband in Bangladesh?",
      rule: "Domestic Violence (Prevention and Protection) Act 2010: Provides civil protection orders. Penal Code 1860: Physical assault is grievous or simple hurt (S.323-325). Nari O Shishu Nirjatan Daman Ain 2000: Covers physical and mental torture of wife. Family Court Ordinance 1985: Maintenance claim.",
      application: "A battered wife can: (1) File FIR for assault at police station, (2) Apply for Protection Order at court under Domestic Violence Act 2010, (3) Apply for Maintenance at Family Court, (4) Seek divorce and dower payment. Both criminal and civil remedies run simultaneously.",
      conclusion: "**If facing domestic violence:**\n1. File FIR at Police Station for assault (hurt — S.323/325)\n2. Apply for Protection Order — nearest court, no fee\n3. Apply for Maintenance at Family Court\n4. Call National Helpline: 10921\n5. Seek shelter: One-Stop Crisis Centre at medical colleges\n\n⚠️ You do not need to tolerate domestic violence. Legal protection is available.\n\n📄 Domestic violence full guide — ৳999",
    },
    escalate: true,
    escalateReason: "Domestic violence victims need immediate protection. WhatsApp NLC for urgent referral.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-036",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["online fraud money", "internet scam", "অনলাইন প্রতারণা", "facebook scam", "cybercrime money fraud"],
    question: "I was defrauded online and lost money — what case can I file?",
    irac: {
      issue: "What criminal remedies exist for a victim of online financial fraud in Bangladesh?",
      rule: "Two sets of laws apply: (1) Penal Code S.420 (cheating — up to 7 years), S.406 (criminal breach of trust — up to 3 years). (2) Cyber Security Act 2023 — online fraud/false information causing financial loss.",
      application: "Collect all evidence: screenshots, transaction records, account details, chat logs. File FIR at local police station AND file complaint at Cyber Crime Unit. Both criminal proceedings run simultaneously. Can also file civil money recovery suit.",
      conclusion: "**Online fraud — file:**\n1. FIR at local police station (S.420 Penal Code — cheating)\n2. Complaint to Cyber Crime Unit — cybercrime.police.gov.bd\n3. Complaint to Bangladesh Bank (if bank involved)\n\n**Evidence to preserve:**\n• Screenshots of all conversations\n• Transaction receipts\n• Account/phone numbers used by fraudster\n• Any contract or promise made\n\n📋 Online fraud complaint guide — ৳99 | 📄 Full procedure — ৳999",
    },
    escalate: false,
    relatedRules: ["cr-cyber-001"],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-037",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["witness rights", "witness protection", "সাক্ষী অধিকার", "testify court", "witness court"],
    question: "What are the rights and duties of a witness in a criminal case?",
    irac: {
      issue: "What rights and obligations does a witness have in Bangladesh criminal proceedings?",
      rule: "Evidence Act 1872: A witness must tell the truth on oath — perjury (false testimony) is punishable under Penal Code S.193 up to 7 years. Witnesses can be compelled to appear by summons. A witness cannot be forced to answer questions that incriminate themselves (self-incrimination privilege).",
      application: "If summoned as witness, you must appear or face contempt of court. You must answer all questions truthfully except those that might incriminate you. Threatening a witness is criminal intimidation (S.506) and obstruction of justice.",
      conclusion: "**Witness rights:**\n• Right against self-incrimination\n• Right to have questions interpreted\n• Right to object to irrelevant or harassing questions\n\n**Witness duties:**\n• Must appear when summoned (or face contempt)\n• Must take oath and tell the truth\n• Must answer all lawful questions\n\n**Perjury (false testimony):** Up to 7 years (S.193 Penal Code)\n\n📋 Witness guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-038",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["juvenile crime", "child offender", "minor crime", "শিশু অপরাধ", "child criminal"],
    question: "What happens if a child commits a crime in Bangladesh?",
    irac: {
      issue: "How does Bangladesh law treat criminal offences committed by children?",
      rule: "Children Act 2013: A child is anyone below 18. Children cannot be imprisoned in adult jails. Cases involving child offenders are heard by Children Court. Children below 9 years cannot commit an offence (no criminal responsibility). Punishment for children: reformatory measures, probation, Certified Institute — not adult prison.",
      application: "If a child (under 18) is arrested, they must be kept in a Child Development Centre (not adult jail) and their case heard in Children Court. The emphasis is on rehabilitation, not punishment. Parents/guardians must be notified immediately.",
      conclusion: "**Child offender (under 18) — Bangladesh:**\n• Cannot be sentenced to adult prison\n• Case heard in Children Court\n• Punishment: probation, community service, Certified Institute (reformatory)\n• Child's identity cannot be published in media\n• Below 9 years: no criminal responsibility\n\n📋 Children Act guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-039",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["how long criminal case takes", "criminal case duration", "মামলা কতদিন চলে", "trial duration bangladesh"],
    question: "How long does a criminal case take in Bangladesh?",
    irac: {
      issue: "What is the typical duration of a criminal case in Bangladesh courts?",
      rule: "There is no fixed time limit for criminal trials under CrPC, but Speedy Trial Tribunal Act 2002 created fast-track courts for serious crimes. Regular Magistrate Court cases: 1-5 years. Sessions Court: 2-7 years. Special tribunal cases (Speedy Trial, Nari Shishu): targeted 135 days per case (rarely achieved in practice).",
      application: "In reality, Bangladesh criminal cases often take 5-15 years due to witness delays, adjournments, and court backlogs. Speedy Trial Tribunals handle: murder, rape, robbery, kidnapping, acid attacks and aim for faster resolution.",
      conclusion: "**Realistic timelines:**\n• Magistrate Court (minor): 1–3 years\n• Sessions Court (serious): 3–10 years\n• Speedy Trial Tribunal: 1–3 years\n• High Court appeal: additional 2–5 years\n• Appellate Division: additional 2–7 years\n\nTotal from FIR to final judgment in serious cases: often 10–20 years.\n\n📋 Criminal case guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-040",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["hartal violence crime", "political violence", "section 144", "curfew", "unlawful assembly", "বেআইনি সমাবেশ"],
    question: "What is unlawful assembly and what is the punishment?",
    irac: {
      issue: "How does Bangladesh law define unlawful assembly and what punishment applies?",
      rule: "Penal Code 1860: Section 141 — Unlawful assembly = 5 or more persons with common object to commit a cognizable offence, use force, resist legal process, or compel government. Section 143: Punishment up to 6 months or fine. Section 144 CrPC: Magistrate can prohibit assembly of 5 or more when there is danger to public order.",
      application: "Participating in an assembly that turns violent makes all members potentially liable even if you personally did not commit violence — doctrine of common intention. Section 144 prohibitory orders are commonly used during political tensions.",
      conclusion: "**Unlawful Assembly (S.141-143):**\n• Being member: Up to 6 months or fine (S.143)\n• With deadly weapon (S.144): Up to 2 years\n• Rioting (S.147): Up to 2 years\n• Rioting with deadly weapon (S.148): Up to 3 years\n\nSection 144 CrPC order violation: up to 6 months.\n\n📋 Criminal law notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  // ════════════════════════════════════════════════════════════
  // EVIDENCE LAW
  // ════════════════════════════════════════════════════════════

  {
    id: "cr-qa-041",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["burden of proof criminal", "proof beyond doubt", "প্রমাণের ভার", "evidence standard", "who must prove"],
    question: "Who has to prove a criminal case — prosecution or accused?",
    irac: {
      issue: "What is the standard and burden of proof in Bangladesh criminal cases?",
      rule: "Evidence Act 1872 + Constitution: In criminal cases, the prosecution must prove the accused's guilt beyond reasonable doubt. The accused is presumed innocent. The burden never shifts to the accused to prove innocence — except in specific statutory exceptions (e.g., drug possession — possession itself creates presumption of trafficking).",
      application: "If the prosecution fails to prove any element of the offence beyond reasonable doubt, the accused must be acquitted. A reasonable doubt in the judge's mind = acquittal. The defence does not need to prove innocence — only raise a reasonable doubt.",
      conclusion: "**Burden of proof in criminal cases:**\n\n✦ Who must prove: **Prosecution**\n✦ Standard: **Beyond reasonable doubt** (highest standard in law)\n✦ Accused presumed: **Innocent** until proven guilty\n✦ Accused duty: None — only raise reasonable doubt\n✦ Exception: Certain special laws create reverse burden on accused\n\n📋 Evidence law notes — ৳99 | 📄 Full evidence guide — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-042",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["confession police", "statement police valid", "পুলিশের কাছে স্বীকারোক্তি", "police confession admissible"],
    question: "Is a confession made to police valid in court?",
    irac: {
      issue: "Are confessions made to police officers admissible as evidence in Bangladesh criminal courts?",
      rule: "Evidence Act 1872, Section 25: A confession made to a police officer is NOT admissible in evidence against the accused. Section 26: A confession made while in police custody is also inadmissible unless made in the immediate presence of a Magistrate. Section 164 CrPC: Confession recorded by Magistrate IS admissible.",
      application: "This rule exists to prevent forced confessions under torture. Even if a person confesses everything to police, that confession cannot be used against them in court. Only a confession recorded by a Judicial Magistrate under Section 164 CrPC — voluntarily and freely — is admissible.",
      conclusion: "**Confession to police:** ❌ NOT admissible in court.\n**Confession in police custody (without Magistrate):** ❌ NOT admissible.\n**Confession before Magistrate (S.164 CrPC):** ✅ Admissible.\n\n⚠️ Never sign any statement given to police without lawyer present — it may be used against you indirectly.\n\n📋 Evidence rights guide — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-043",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["dying declaration", "মৃত্যুকালীন জবানবন্দি", "dying statement", "death bed statement"],
    question: "What is a dying declaration and is it valid in court?",
    irac: {
      issue: "Is a statement made by a dying person admissible as evidence in Bangladesh criminal courts?",
      rule: "Evidence Act 1872, Section 32(1): Statements made by a person about the cause of their death or circumstances of the transaction resulting in their death are admissible — even without cross-examination — if the person dies. This is called a dying declaration.",
      application: "A murder victim tells a doctor or Magistrate before dying 'A stabbed me' → that statement is admissible as dying declaration even though the victim cannot be cross-examined. Courts treat dying declarations as strong evidence as a dying person has no motive to lie.",
      conclusion: "**Dying Declaration:**\n✅ Admissible in court without cross-examination\n✅ Considered strong evidence (no motive to lie at death)\n✅ Can be basis for conviction alone if credible\n\nBest recorded by: Magistrate or doctor.\nVerbal dying declaration to family member is also admissible but weaker.\n\n📋 Evidence law notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  // ════════════════════════════════════════════════════════════
  // BAR EXAM / LAW STUDENT QUESTIONS
  // ════════════════════════════════════════════════════════════

  {
    id: "cr-qa-044",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["mens rea", "actus reus", "criminal intention", "criminal act", "মানসিক উপাদান অপরাধ", "elements of crime"],
    question: "What are the essential elements of a crime (mens rea and actus reus)?",
    irac: {
      issue: "What elements must be proven to establish criminal liability under Bangladesh law?",
      rule: "Bangladesh criminal law follows the common law principle: crime = actus reus (guilty act) + mens rea (guilty mind). Actus reus = the physical act or omission constituting the crime. Mens rea = the mental element — intention, knowledge, recklessness, or negligence required by the specific offence.",
      application: "Murder: Actus reus = killing a human being. Mens rea = intention to cause death or knowledge that death will result. Theft: Actus reus = moving property. Mens rea = dishonest intention. Without mens rea, most crimes cannot be established — except strict liability offences (rare).",
      conclusion: "**Two elements of crime:**\n\n✦ **Actus Reus** = The guilty act (what was done)\n✦ **Mens Rea** = The guilty mind (what was intended/known)\n\n**Types of Mens Rea:**\n• Intention (most serious)\n• Knowledge\n• Recklessness\n• Negligence (least serious)\n\nStrict liability offences (no mens rea needed): very rare — e.g., some traffic and environmental offences.\n\n📋 Criminal law foundations — ৳99 | 📄 Bar exam guide — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-045",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["private defence", "self defence", "right of private defence", "আত্মরক্ষার অধিকার", "section 96"],
    question: "What is the right of private defence in Bangladesh criminal law?",
    irac: {
      issue: "When can a person use force in self-defence without criminal liability under Bangladesh law?",
      rule: "Penal Code 1860, Sections 96-106: Every person has the right to defend their body and property against any offence. The right extends to causing death only when there is reasonable apprehension of death, grievous hurt, rape, kidnapping, robbery, or housebreaking at night. The force used must not exceed what is reasonably necessary.",
      application: "A person attacked with a knife can use force to defend themselves. If the threat is of death or grievous hurt, they can even kill the attacker in self-defence — this is a complete defence. But shooting an unarmed thief running away = exceeds private defence.",
      conclusion: "**Right of Private Defence:**\n\n✅ Defence of body: Against any assault causing apprehension of harm\n✅ Causing death justified when apprehension of: Death, Grievous Hurt, Rape, Kidnapping, Acid attack\n✅ Defence of property: Against theft, robbery, mischief, trespass\n\n❌ Cannot exceed what is necessary\n❌ Cannot be used when there is time to seek public authority help\n❌ Not available as aggressor\n\n📋 Private defence exam notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-046",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["insanity defence", "unsound mind", "mental disorder crime", "section 84", "অপ্রকৃতিস্থ অপরাধ"],
    question: "Can a mentally ill person be convicted of a crime?",
    irac: {
      issue: "What is the legal position regarding criminal liability of persons of unsound mind in Bangladesh?",
      rule: "Penal Code 1860, Section 84: Nothing is an offence done by a person who, at the time of doing it, by reason of unsoundness of mind, is incapable of knowing the nature of the act, or that the act is wrong or contrary to law.",
      application: "The defence of insanity requires proving: (1) at the time of the act, (2) the person was of unsound mind, (3) which made them incapable of knowing the act was wrong. Medical evidence is critical. Court may order psychiatric evaluation. If found not guilty by reason of insanity, the person is sent to a mental institution.",
      conclusion: "**Insanity defence (S.84):**\n\nIf proven → Not guilty (complete defence)\nBurden: On accused to prove insanity on balance of probabilities\nResult: Sent to psychiatric institution by court order\n\nTemporary insanity at time of act = defence.\nKnowing an act is wrong but being unable to control = NO defence.\n\n📋 Criminal law exam notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-047",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["abetment", "section 107", "সহায়তাকারী শাস্তি", "aiding crime", "helping commit crime"],
    question: "What is abetment — can you be punished for helping someone commit a crime?",
    irac: {
      issue: "What is criminal abetment and what punishment applies under Bangladesh law?",
      rule: "Penal Code 1860, Section 107: Abetment = instigating, conspiring, or intentionally aiding a person to commit an offence. Section 109: If the offence is committed, the abettor receives the same punishment as the principal offender. Section 115: Abetting an offence punishable with death — up to 7 years if not committed.",
      application: "Hiring someone to commit murder and that murder is committed = abettor gets same punishment as murderer (death or life imprisonment). Providing a weapon knowing it will be used to commit robbery = abetment of robbery.",
      conclusion: "**Abetment:**\n\n✦ Abettor = same punishment as principal if offence committed\n✦ Abetment of murder (if committed) → Death or life imprisonment\n✦ Abetment where offence not committed → Punishment varies by offence type\n\nThree types of abetment:\n1. Instigation (urging)\n2. Conspiracy (planning together)\n3. Aid (assisting, facilitating)\n\n📋 Criminal law exam notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-048",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["common intention", "section 34", "joint offence", "একসাথে অপরাধ", "joint liability crime"],
    question: "What is common intention — can all accused be punished equally?",
    irac: {
      issue: "How does Section 34 of the Penal Code make all members of a group equally liable for a criminal act?",
      rule: "Penal Code 1860, Section 34: When a criminal act is done by several persons in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.",
      application: "A, B, C plan to rob a shop. During the robbery, A shoots and kills the shopkeeper. Even though only A fired the gun — B and C are equally liable for murder under Section 34 because they acted with common intention. All three can receive the death penalty.",
      conclusion: "**Common Intention (S.34):**\n\nAll participants = equal liability even if only one physically committed the act.\n\nRequirements:\n• Prior meeting of minds (common intention)\n• Act done in furtherance of that intention\n• Each person participated (need not do the actual act)\n\n⚠️ Being present at a crime with common intention = full criminal liability.\n\n📋 Criminal law exam notes — ৳99",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-049",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["writ habeas corpus", "illegal detention", "হেবিয়াস কর্পাস", "release from illegal detention", "habeas corpus bangladesh"],
    question: "What is a Habeas Corpus writ and how do I use it?",
    irac: {
      issue: "What is a Habeas Corpus writ petition and how can it secure release from unlawful detention in Bangladesh?",
      rule: "Constitution of Bangladesh, Article 102(2)(b)(i): The High Court Division can direct any person detaining another to produce the body before court and show cause for detention. If detention is unlawful, the court orders immediate release. This is the Habeas Corpus writ.",
      application: "If a person is detained beyond 24 hours without Magistrate production, held without charge, or detained under an illegal order — a family member or lawyer can file Habeas Corpus petition at High Court Division. The court acts urgently — usually within hours or days.",
      conclusion: "**Habeas Corpus — Release from illegal detention:**\n\nWho can file: Any person on behalf of detainee — family, friend, lawyer\nWhere: High Court Division, Dhaka\nHow urgent: Court acts same day or next day in emergency\nResult: If detention illegal → immediate release ordered\n\n⚠️ File immediately — time matters in illegal detention.\n\n📄 Habeas Corpus guide — ৳1,999\nWhatsApp NLC for urgent referral.",
    },
    escalate: true,
    escalateReason: "Habeas Corpus writ requires immediate High Court filing. WhatsApp NLC urgently.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  {
    id: "cr-qa-050",
    area: "criminal",
    jurisdiction: "BD",
    triggerKeywords: ["double jeopardy", "tried twice same offence", "একই মামলা দুইবার", "section 403", "acquittal retrial"],
    question: "Can someone be tried twice for the same crime in Bangladesh?",
    irac: {
      issue: "Does Bangladesh law protect an accused from being tried twice for the same offence?",
      rule: "Constitution of Bangladesh, Article 35(2): No person shall be prosecuted and punished for the same offence more than once. CrPC Section 403: A person who has been convicted or acquitted of an offence may plead such conviction or acquittal as a bar to any subsequent charge for the same offence.",
      application: "If a court acquits A of murder — the state cannot re-try A for the same murder in another court. However, the state can appeal the acquittal to a higher court — that is not double jeopardy because it is the same proceeding continued, not a new prosecution.",
      conclusion: "**Double Jeopardy — Bangladesh:**\n\n✅ Protected by Constitution Article 35(2)\n✅ Acquittal or conviction = complete bar to retrial for same offence\n\n❌ NOT double jeopardy:\n• Appeal by state against acquittal (same case, higher court)\n• Retrial ordered by High Court due to procedural error\n• Different offence arising from same facts\n\n📋 Constitutional rights notes — ৳99 | 📄 Bar exam guide — ৳999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
];

const criminalModule: KnowledgeModule = {
  area: "criminal",
  label: "Criminal Law — Penal Code, CrPC & Special Laws",
  description: "50 Q&A covering Penal Code offences and punishments, CrPC procedures, special laws (Nari O Shishu, Cyber Security, Narcotics), case scenarios, and evidence law. For law students, bar exam preparation, and citizens seeking legal guidance.",
  rules,
  qaBank,
};

export default criminalModule;
