// ─── JesAI Property & Land Knowledge Module ──────────────────
// NLC validated — Nazmul, Advocate, Supreme Court of Bangladesh
// 212 topics covered across 12 categories
// Free tier: awareness + public info only
// Paid tier: document lists (99-399 Tk), procedures (999-19,999 Tk)
// No legal advice. No offline service. Referral via WhatsApp only.

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "prop-title-001",
    area: "property",
    jurisdiction: "BD",
    title: "Title Dispute — Specific Relief Act 1877",
    rule: "A person whose title to immovable property is disputed may file a declaration suit under Section 42 of the Specific Relief Act 1877 to obtain a court declaration of their title. The burden of proof lies on the plaintiff to establish superior title.",
    source: "Specific Relief Act 1877, Section 42; Code of Civil Procedure 1908",
    certainty: "confirmed",
    tags: ["title dispute", "declaration suit", "ownership", "specific relief"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-limitation-001",
    area: "property",
    jurisdiction: "BD",
    title: "Limitation Period — Property Suits",
    rule: "For suits to recover possession of immovable property, the limitation period is 12 years from the date of dispossession. For title declaration suits, it is also 12 years. For mortgage redemption, it is 30 years.",
    source: "Limitation Act 1908, Articles 142, 144, 147",
    certainty: "confirmed",
    tags: ["limitation", "12 years", "possession", "title suit", "time limit"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-adverse-001",
    area: "property",
    jurisdiction: "BD",
    title: "Adverse Possession — 12 Year Rule",
    rule: "A person in continuous, open, hostile, and exclusive possession of land for 12 years acquires title by adverse possession under the Limitation Act 1908. The original owner's right to sue is extinguished after 12 years.",
    source: "Limitation Act 1908, Article 142; State Acquisition and Tenancy Act 1950",
    certainty: "confirmed",
    tags: ["adverse possession", "squatter", "12 years", "limitation", "possession"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-mutation-001",
    area: "property",
    jurisdiction: "BD",
    title: "Mutation — Legal Requirement After Transfer",
    rule: "After any transfer of land ownership, the new owner must apply for mutation (Namajaari) at the local Union Land Office. Mutation updates the government khatian record. Without mutation, the transferee cannot pay land tax or legally possess the land in their name.",
    source: "State Acquisition and Tenancy Act 1950; Land Reform Ordinance 1984",
    certainty: "confirmed",
    tags: ["mutation", "namajaari", "khatian", "land record", "transfer", "ownership update"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-registration-001",
    area: "property",
    jurisdiction: "BD",
    title: "Mandatory Registration of Property Documents",
    rule: "Under the Registration Act 1908, any document transferring immovable property worth BDT 100 or more must be registered at the Sub-Registrar's office. An unregistered deed of transfer has no legal effect and cannot be used as evidence in court.",
    source: "Registration Act 1908, Sections 17, 49",
    certainty: "confirmed",
    tags: ["registration", "deed", "sub-registrar", "transfer", "unregistered"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-mortgage-001",
    area: "property",
    jurisdiction: "BD",
    title: "Artha Rin Adalat — Bank Loan Recovery",
    rule: "Banks and financial institutions recover defaulted loans secured by property through the Artha Rin Adalat (Money Loan Court) under the Artha Rin Adalat Ain 2003. The court can order attachment and auction of the mortgaged property.",
    source: "Artha Rin Adalat Ain 2003",
    certainty: "confirmed",
    tags: ["artha rin adalat", "bank", "loan default", "foreclosure", "mortgage", "auction"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-preemption-001",
    area: "property",
    jurisdiction: "BD",
    title: "Pre-emption Right (Shafi) — Co-owner/Neighbour",
    rule: "Under the State Acquisition and Tenancy Act 1950, a co-sharer or adjoining landowner has the right of pre-emption (shafi) to purchase land sold to an outsider at the same price. The pre-emption suit must be filed within 4 months of the sale registration.",
    source: "State Acquisition and Tenancy Act 1950, Sections 96-100",
    certainty: "confirmed",
    tags: ["preemption", "shafi", "co-owner", "neighbour", "right of first refusal", "4 months"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-inheritance-001",
    area: "property",
    jurisdiction: "BD",
    title: "Muslim Inheritance — Hanafi Rules",
    rule: "Under Muslim personal law (Hanafi school applied in Bangladesh), property passes on death to heirs according to fixed Quranic shares. A son receives double the share of a daughter. Wife receives 1/8 if children exist, 1/4 if no children. A Muslim cannot disinherit an heir by will beyond 1/3 of estate.",
    source: "Muslim Personal Law (Shariat) Application Act 1937; Succession Act 1925 (for probate)",
    certainty: "confirmed",
    tags: ["inheritance", "muslim", "hanafi", "heir", "shares", "succession", "will", "estate"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-cheque-001",
    area: "property",
    jurisdiction: "BD",
    title: "Cheque Dishonour — Criminal Liability",
    rule: "Under the Negotiable Instruments Act 1881 (Section 138 as amended), dishonour of a cheque for insufficiency of funds is a criminal offence. The payee must send a legal notice within 30 days of dishonour. If unpaid within 30 days of notice, a criminal complaint may be filed within 30 days thereafter.",
    source: "Negotiable Instruments Act 1881, Section 138",
    certainty: "confirmed",
    tags: ["cheque bounce", "dishonour", "negotiable instruments", "criminal", "notice", "30 days"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-khas-001",
    area: "property",
    jurisdiction: "BD",
    title: "Khas Land — Government Ownership",
    rule: "Khas land is government-owned land not held by any private party. Under the Land Reform Ordinance 1984 and subsequent circulars, khas land can be settled (allocated) to landless people and certain eligible applicants through the District Administration. Unauthorized occupation of khas land is illegal.",
    source: "Land Reform Ordinance 1984; State Acquisition and Tenancy Act 1950",
    certainty: "confirmed",
    tags: ["khas land", "government land", "settlement", "DC office", "landless", "khas"],
    lastVerified: "2025-03-09",
  },
];

const qaBank: QAEntry[] = [
  // ── CATEGORY 1: TITLE DISPUTES ────────────────────────────
  {
    id: "prop-qa-title-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["title dispute", "ownership dispute", "who owns", "my land taken", "ownership challenge", "land ownership"],
    question: "Someone is challenging my ownership of land — what can I do?",
    irac: {
      issue: "Whether a landowner whose title is being challenged can obtain legal recognition of their ownership.",
      rule: "Under Section 42 of the Specific Relief Act 1877, any person entitled to any legal character or right to any property may seek a court declaration. The Transfer of Property Act 1882 and Registration Act 1908 govern valid transfer and proof of ownership.",
      application: "If your title documents (deed, khatian, mutation record) are in order and registered, you have strong grounds to defend ownership. A declaration suit filed in Civil Court establishes your title formally. If the challenge involves a forged deed, a cancellation suit must also be filed.",
      conclusion: "Gather all title documents immediately: registered deed, CS/RS/BS khatian, mutation record, tax receipts, possession evidence. Do not vacate the land. File a declaration suit in Civil Court if challenged formally.\n\n📋 **Want the full document checklist for a title suit?** — Document List: ৳99\n📄 **Want step-by-step procedure + court filing guide?** — Procedure Guide: ৳999",
    },
    escalate: false,
    relatedRules: ["prop-title-001", "prop-registration-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-title-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["lost deed", "deed lost", "lost title", "missing deed", "duplicate deed"],
    question: "I lost my land deed — how do I get a duplicate?",
    irac: {
      issue: "Whether a landowner who has lost their original registered deed can obtain a certified copy and establish their ownership.",
      rule: "Under the Registration Act 1908, certified copies of registered documents are available from the Sub-Registrar's office. A certified copy has the same evidentiary value as the original for court purposes.",
      application: "A lost registered deed can be replaced with a certified copy from the Sub-Registrar office where it was originally registered. You need the deed number, registration date, and volume/book reference. Additionally, your khatian and mutation records independently confirm ownership.",
      conclusion: "Apply for a certified copy at the Sub-Registrar's office. You will need: deed number, registration year, your NID. Fee is approximately BDT 200-500 depending on pages.\n\n📋 **Want the exact application form and documents list?** — Document List: ৳99\n📄 **Want full procedure + Sub-Registrar office guide?** — Procedure Guide: ৳999",
    },
    escalate: false,
    relatedRules: ["prop-registration-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-title-003",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["forged deed", "fake deed", "fraudulent deed", "deed forgery", "fake registration"],
    question: "Someone has forged a deed to claim my land — what can I do?",
    irac: {
      issue: "Whether a landowner can challenge a forged or fraudulent deed used to claim their property.",
      rule: "Forgery of a deed is a criminal offence under Penal Code 1860 (Sections 463-477A). Civilly, a fraudulent deed can be cancelled under Section 31 of the Specific Relief Act 1877. Both criminal and civil remedies run simultaneously.",
      application: "You can file a criminal case (FIR) at the police station for forgery/fraud AND file a civil suit for cancellation of the fraudulent deed in Civil Court. An injunction can be obtained immediately to stop any further transfer of the land pending court decision.",
      conclusion: "Act immediately — file both FIR and civil suit. Every day of delay risks further transfer of your land.\n\n⚠️ This requires professional legal action. WhatsApp NLC for referral.\n\n📋 **Document checklist for forgery case?** — Document List: ৳199\n📄 **Full procedure guide — FIR + civil suit + injunction?** — Procedure Guide: ৳1,999",
    },
    escalate: true,
    escalateReason: "Forged deed cases require immediate court action. Contact NLC via WhatsApp for referral to a qualified advocate.",
    relatedRules: ["prop-title-001", "prop-registration-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-title-004",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["adverse possession", "long possession", "living 12 years", "occupying land", "possessing land for years"],
    question: "I have been living on land for many years — can I claim ownership?",
    irac: {
      issue: "Whether long-term continuous possession of land gives rise to a legal claim of ownership through adverse possession.",
      rule: "Under the Limitation Act 1908 (Article 142), a person in continuous, open, hostile, exclusive possession of land for 12 years acquires prescriptive title. The original owner's right to sue is extinguished. The possession must be without the owner's permission.",
      application: "If you have been in continuous, uninterrupted, open, and exclusive possession for 12+ years without the owner's permission and without their interference, you may have acquired title by adverse possession. Evidence needed: neighbours' testimony, utility bills, tax payment receipts, old photographs.",
      conclusion: "Gather all evidence of continuous possession. File a declaratory suit in Civil Court establishing your title through adverse possession.\n\n📋 **Document and evidence checklist?** — Document List: ৳99\n📄 **Full procedure guide for adverse possession suit?** — Procedure Guide: ৳999",
    },
    escalate: false,
    relatedRules: ["prop-adverse-001", "prop-limitation-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-title-005",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["khas land", "khas", "government land", "settle khas", "khas allocation"],
    question: "How can I apply for khas land settlement?",
    irac: {
      issue: "Whether an eligible person can apply to the government for settlement (allocation) of khas land.",
      rule: "Under the Land Reform Ordinance 1984 and DC office circulars, eligible landless families and individuals may apply for khas land settlement through the Upazila Land Office. Priority is given to landless farmers, widows, and displaced persons.",
      application: "Applications are submitted at the Upazila Land Office (AC Land). Eligibility: Bangladeshi citizen, owning less than 0.5 acres of land, not previously allotted khas land. The DC office verifies eligibility and issues a settlement khatian.",
      conclusion: "Apply at your Upazila AC Land office with eligibility documents.\n\n📋 **Full eligibility criteria + document list?** — Document List: ৳99\n📄 **Step-by-step application procedure + office guide?** — Procedure Guide: ৳999",
    },
    escalate: false,
    relatedRules: ["prop-khas-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 2: BOUNDARY & ENCROACHMENT ──────────────────
  {
    id: "prop-qa-boundary-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["boundary dispute", "neighbour encroachment", "encroachment", "fence dispute", "wall dispute", "neighbour took land"],
    question: "My neighbour has encroached on my land — what can I do?",
    irac: {
      issue: "Whether a landowner can recover land encroached upon by a neighbour.",
      rule: "Under the Code of Civil Procedure 1908, a landowner can file a suit for recovery of possession. An interim injunction can be obtained to stop further encroachment immediately. The Transfer of Property Act 1882 and survey records define legal boundaries.",
      application: "You can obtain an urgent interim injunction from Civil Court to stop the neighbour from further encroachment. Then file a suit for recovery of the encroached portion. Survey records (CS/RS/BS maps) from the land office establish the true boundary.",
      conclusion: "First: obtain survey records from AC Land office to confirm your boundary. Second: send a written legal notice to neighbour. Third: apply for interim injunction if they continue.\n\n📋 **Document checklist for encroachment suit?** — Document List: ৳99\n📄 **Full procedure guide including injunction application?** — Procedure Guide: ৳1,499",
    },
    escalate: false,
    relatedRules: ["prop-title-001", "prop-limitation-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-boundary-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["river erosion", "erosion land", "river took land", "char land", "accretion"],
    question: "My land was eroded by the river — do I still own it?",
    irac: {
      issue: "Whether a landowner retains title to land lost due to river erosion, and whether they can reclaim land if it resurfaces.",
      rule: "Under the State Acquisition and Tenancy Act 1950, land lost to river erosion retains its legal status in records. If land resurfaces (accretes) within 30 years, the original owner can reclaim it. Newly formed char land belongs to the government until settled.",
      application: "If your land was eroded within 30 years, maintain your khatian record and apply to the AC Land office to reclaim when it resurfaces. Do not abandon your khatian record — it is your legal proof of prior ownership.",
      conclusion: "Keep your khatian and prior records. Apply to AC Land office if land resurfaces. Newly formed char requires fresh settlement application.\n\n📋 **Document list for erosion/char land claim?** — Document List: ৳199\n📄 **Full procedure guide for char land reclaim?** — Procedure Guide: ৳1,999",
    },
    escalate: false,
    relatedRules: ["prop-khas-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 3: INHERITANCE & SUCCESSION ─────────────────
  {
    id: "prop-qa-inherit-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["inheritance", "inherit", "father died", "mother died", "property after death", "who gets property", "succession"],
    question: "My father died — how is his property divided among heirs?",
    irac: {
      issue: "How immovable and movable property of a deceased Muslim is distributed among surviving heirs under Bangladesh law.",
      rule: "Under Muslim personal law (Hanafi school), property distributes according to fixed Quranic shares. Son: twice daughter's share. Wife: 1/8 with children, 1/4 without. Daughter: half of son's share. Parents: 1/6 each if deceased has children.",
      application: "First step is to determine all surviving heirs and their relationship to the deceased. Then calculate shares under Hanafi rules. All heirs must agree on partition or file a partition suit. A Succession Certificate from court may be needed for movable assets like bank accounts.",
      conclusion: "Prepare the heir list with all family members. Calculate shares. For movable assets apply for Succession Certificate from court. For land — file partition suit or execute family settlement deed.\n\n📋 **Heir list + share calculation worksheet?** — Document List: ৳199\n📄 **Full inheritance procedure + Succession Certificate guide?** — Procedure Guide: ৳1,999\n📄 **Complete inheritance document pack?** — Full Pack: ৳4,999",
    },
    escalate: false,
    relatedRules: ["prop-inheritance-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-inherit-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["probate", "will", "wasiyat", "bequest", "testamentary"],
    question: "My father left a will — how do I execute it legally?",
    irac: {
      issue: "How a will (wasiyat) left by a deceased Muslim is legally executed in Bangladesh.",
      rule: "Under Muslim personal law, a will is valid only up to 1/3 of the estate — the remaining 2/3 distributes by Quranic shares. A will cannot benefit an heir who already inherits. Probate of a will is obtained from the District Judge's court under the Succession Act 1925.",
      application: "File a probate petition in District Judge's court with the original will, death certificate, and list of heirs. The court issues Letters of Administration or Probate after hearing all parties. Only then can assets be transferred per the will.",
      conclusion: "Do not distribute assets without court probate — it can be challenged later.\n\n📋 **Probate petition documents list?** — Document List: ৳199\n📄 **Full probate procedure guide?** — Procedure Guide: ৳1,999",
    },
    escalate: false,
    relatedRules: ["prop-inheritance-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-inherit-003",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["partition heirs", "divide property", "partition land", "heirs partition", "share property among brothers"],
    question: "How do we divide inherited land among siblings?",
    irac: {
      issue: "The legal process for partitioning inherited land among multiple heirs.",
      rule: "Under the Code of Civil Procedure 1908 (Order 20 Rule 18), co-heirs can file a partition suit in Civil Court. If all heirs agree, a registered family settlement deed (raji naama) is faster and cheaper than a court suit.",
      application: "Option 1 — Mutual agreement: All heirs sign a registered partition deed at Sub-Registrar office. Each heir then mutates their share separately. Option 2 — Court partition: File partition suit in Civil Court. Court appoints a Commissioner who physically measures and divides the land.",
      conclusion: "Mutual agreement with registered deed is faster (1-3 months, lower cost). Court partition takes 2-5 years but is binding on all parties.\n\n📋 **Partition deed + mutation document list?** — Document List: ৳199\n📄 **Full partition procedure (both options)?** — Procedure Guide: ৳1,999\n📄 **Family settlement deed template + filing guide?** — Full Pack: ৳4,999",
    },
    escalate: false,
    relatedRules: ["prop-inheritance-001", "prop-mutation-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 4: JOINT PROPERTY & PRE-EMPTION ─────────────
  {
    id: "prop-qa-preemption-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["preemption", "shafi", "co-sharer sold", "neighbour sold land", "right to buy first", "pre-emption"],
    question: "My co-sharer sold land to an outsider without telling me — can I claim it?",
    irac: {
      issue: "Whether a co-sharer has the right to pre-empt a sale of jointly owned land to an outsider.",
      rule: "Under the State Acquisition and Tenancy Act 1950 (Sections 96-100), a co-sharer in land has the right of pre-emption (shafi) — the right to purchase the sold share at the same price paid by the buyer. The pre-emption suit must be filed within 4 months of the sale deed registration.",
      application: "You must file the pre-emption suit within 4 months of the registration date — not from when you found out. The court requires you to deposit the purchase price. If successful, the sale to the outsider is set aside and you acquire the share.",
      conclusion: "⚠️ The 4-month deadline is absolute. Check the registration date immediately.\n\n📋 **Pre-emption suit document list?** — Document List: ৳199\n📄 **Full pre-emption procedure + deposit guide?** — Procedure Guide: ৳1,999",
    },
    escalate: true,
    escalateReason: "4-month limitation is strict — file immediately. WhatsApp NLC for urgent referral.",
    relatedRules: ["prop-preemption-001", "prop-limitation-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 5: LAND SALE & MONEY RECOVERY ───────────────
  {
    id: "prop-qa-sale-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["baynama", "advance money", "land advance", "sale agreement", "buyer not paying", "seller not giving land"],
    question: "I paid advance money for land but the seller is not giving it — what can I do?",
    irac: {
      issue: "Whether a buyer who has paid an advance (baynama) for land can enforce the sale or recover their money.",
      rule: "A baynama (agreement to sell) is a binding contract under the Contract Act 1872. Under Section 12 of the Specific Relief Act 1877, a buyer can file a suit for specific performance to compel the seller to complete the sale. Alternatively, the buyer can claim refund with damages.",
      application: "You can file a suit for specific performance in Civil Court to force the seller to execute the final deed. Or you can claim refund of advance plus damages for breach. A baynama should be registered for stronger legal standing — an unregistered baynama has weaker evidentiary value.",
      conclusion: "File suit for specific performance within 3 years of breach (Limitation Act). Keep all payment receipts and the original baynama.\n\n📋 **Document list for specific performance suit?** — Document List: ৳199\n📄 **Full procedure guide for baynama enforcement?** — Procedure Guide: ৳1,999",
    },
    escalate: false,
    relatedRules: ["prop-registration-001", "prop-limitation-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-sale-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["power of attorney fraud", "POA fraud", "attorney fraud", "power of attorney land"],
    question: "Someone used a fake power of attorney to sell my land — what can I do?",
    irac: {
      issue: "Whether a landowner can recover land sold through a fraudulent or forged power of attorney.",
      rule: "A power of attorney must be authenticated. Fraudulent use of a POA to transfer property is a criminal offence (Penal Code 1860, Sections 463-468). The transfer can be set aside under Section 31 of the Specific Relief Act 1877 as being obtained by fraud.",
      application: "File FIR for forgery AND file civil suit to cancel the fraudulent transfer. Apply for injunction immediately to stop further dealings with the land. Also report to the Sub-Registrar office to flag the registration.",
      conclusion: "⚠️ Act immediately — every day risks further transfer.\n\nWhatsApp NLC for urgent referral to advocate.\n\n📄 **Full procedure guide — FIR + cancellation suit?** — Procedure Guide: ৳2,999",
    },
    escalate: true,
    escalateReason: "POA fraud requires immediate criminal and civil action. Contact NLC via WhatsApp urgently.",
    relatedRules: ["prop-title-001", "prop-registration-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 6: LEASE & TENANCY ──────────────────────────
  {
    id: "prop-qa-eviction-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["evict tenant", "eviction", "tenant not leaving", "tenant overstaying", "rent not paid"],
    question: "My tenant is not paying rent and not leaving — how do I evict them?",
    irac: {
      issue: "Whether a landlord can evict a tenant who fails to pay rent or refuses to vacate.",
      rule: "Under the Premises Rent Control Act 1991, a landlord may file an eviction suit in the Rent Controller Court for non-payment of rent (2 months default) or expiry of tenancy. A court order is required — self-help eviction (cutting utilities, locking out) is illegal.",
      application: "Send written notice to tenant demanding rent payment and/or vacation within 30 days. If ignored, file eviction petition in Rent Controller Court (for residential/commercial premises). For premises not covered by Rent Control Act, file civil suit for eviction.",
      conclusion: "Do NOT cut electricity, water, or forcibly remove tenant — this exposes you to criminal liability.\n\n📋 **Eviction notice template + document list?** — Document List: ৳199\n📄 **Full eviction procedure guide?** — Procedure Guide: ৳1,499",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 7: MORTGAGE & BANK LOAN ─────────────────────
  {
    id: "prop-qa-mortgage-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["loan default", "bank default", "bank taking land", "foreclosure", "artha rin", "mortgage default"],
    question: "I defaulted on a bank loan secured by my land — what will happen?",
    irac: {
      issue: "What legal process a bank follows when a borrower defaults on a loan secured by immovable property in Bangladesh.",
      rule: "Under the Artha Rin Adalat Ain 2003, banks file recovery suits in the Artha Rin Adalat (Money Loan Court). The court can order attachment of the mortgaged property and auction. The borrower can raise defences and also apply for restructuring.",
      application: "Once the bank files suit in Artha Rin Adalat, you will receive a summons. You have the right to file a written statement of defence. You can also approach the bank for loan restructuring — banks often prefer restructuring over lengthy litigation. If the court orders auction, you can challenge the valuation.",
      conclusion: "Do not ignore the summons — a one-sided decree will be passed against you.\n\nContact the bank's loan recovery department for restructuring options before court proceedings begin.\n\n📋 **Document list for Artha Rin Adalat defence?** — Document List: ৳299\n📄 **Full procedure guide — defence + restructuring options?** — Procedure Guide: ৳2,999\n📄 **Complete Artha Rin Adalat defence pack?** — Full Pack: ৳9,999",
    },
    escalate: true,
    escalateReason: "Artha Rin cases move fast. WhatsApp NLC for referral to specialist advocate immediately.",
    relatedRules: ["prop-mortgage-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-mortgage-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["mortgage redemption", "redeem mortgage", "paid loan back", "clear mortgage", "free property from mortgage"],
    question: "I paid back my loan — how do I remove the mortgage from my land?",
    irac: {
      issue: "How a borrower who has repaid a loan obtains release of the mortgage over their property.",
      rule: "Under the Transfer of Property Act 1882 (Section 60), upon repayment of the mortgage debt, the mortgagor has the right to redemption — the mortgagee must re-transfer the property. The bank must issue a No Objection Certificate (NOC) and execute a deed of reconveyance.",
      application: "After full loan repayment, obtain: (1) No Objection Certificate from bank, (2) Reconveyance deed from bank, (3) Register the reconveyance deed at Sub-Registrar's office, (4) Apply for mutation to update khatian. Without registered reconveyance, the mortgage encumbrance remains on record.",
      conclusion: "Get the reconveyance deed registered — an NOC alone is not sufficient to clear your title records.\n\n📋 **Mortgage release document list?** — Document List: ৳199\n📄 **Full mortgage redemption procedure?** — Procedure Guide: ৳1,499",
    },
    escalate: false,
    relatedRules: ["prop-mortgage-001", "prop-registration-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 8: GOVERNMENT ACQUISITION ───────────────────
  {
    id: "prop-qa-acquisition-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["government acquired land", "acquisition", "govt took land", "road project land", "compensation land"],
    question: "The government acquired my land for a road/project — am I getting fair compensation?",
    irac: {
      issue: "Whether a landowner whose property is acquired for a government project receives adequate compensation and what remedies exist if they do not.",
      rule: "Under the Acquisition and Requisition of Immovable Property Act 2017, the government must pay compensation at market value plus 200% solatium (additional compensation). The affected owner can file an objection before the Joint District Judge and appeal to the High Court.",
      application: "When an acquisition notice is served, the Joint District Judge assesses compensation. If you believe the offer is below market value, file a written objection citing comparable land prices in the area. You can also file an appeal against the compensation award.",
      conclusion: "Do not accept compensation cheque without verifying it matches market value — acceptance may waive your right to appeal.\n\n📋 **Objection to compensation — document list?** — Document List: ৳299\n📄 **Full objection + appeal procedure guide?** — Procedure Guide: ৳2,999",
    },
    escalate: false,
    relatedRules: [],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 9: MUTATION & REGISTRATION ──────────────────
  {
    id: "prop-qa-mutation-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["mutation", "namajaari", "khatian update", "name change land", "emutation", "e-mutation"],
    question: "How do I do mutation (namajaari) after buying land?",
    irac: {
      issue: "The legal process for updating land records (mutation/namajaari) in the buyer's name after a land purchase.",
      rule: "Under the State Acquisition and Tenancy Act 1950, mutation is mandatory after any transfer of ownership. Without mutation, the buyer cannot legally pay land tax or possess the land in their name in government records.",
      application: "After registering the deed at Sub-Registrar, apply for mutation at the Upazila Land Office (AC Land). Submit application with required documents. The AC Land office inspects, hears objections from neighbours (public notice), and if satisfied issues mutation khatian.",
      conclusion: "Mutation should be done within 60 days of registration to avoid complications.\n\n📋 **Mutation application document list?** — Document List: ৳99\n📄 **Full mutation procedure guide (e-Mutation + manual)?** — Procedure Guide: ৳999\n📄 **Complete mutation document pack?** — Full Pack: ৳2,999",
    },
    escalate: false,
    relatedRules: ["prop-mutation-001", "prop-registration-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-mutation-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["khatian mismatch", "record mismatch", "wrong khatian", "bs rs cs mismatch", "record correction"],
    question: "My BS/RS/CS khatian records don't match — how do I correct them?",
    irac: {
      issue: "How a landowner corrects discrepancies between different survey records (CS, RS, BS khatian).",
      rule: "Survey record corrections are handled through the Land Survey Tribunal Act 2023. Errors in khatian records can be corrected through the AC Land office for minor clerical errors, or through the Land Survey Tribunal for substantive disputes.",
      application: "For minor errors (spelling, area figure): apply to AC Land office with supporting documents. For substantive mismatches between CS/RS/BS: file a case before the Land Survey Tribunal with all record copies and survey maps.",
      conclusion: "Identify whether the mismatch is clerical (AC Land can fix) or substantive (needs Tribunal).\n\n📋 **Record correction document list?** — Document List: ৳199\n📄 **Full correction procedure guide?** — Procedure Guide: ৳1,499",
    },
    escalate: false,
    relatedRules: ["prop-mutation-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 10: CHEQUE & MONEY DISPUTES ─────────────────
  {
    id: "prop-qa-cheque-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["cheque bounce", "cheque dishonour", "cheque returned", "bounced cheque", "bad cheque"],
    question: "Someone gave me a cheque that bounced — what can I do?",
    irac: {
      issue: "What legal remedy a payee has when a cheque is dishonoured for insufficient funds.",
      rule: "Under the Negotiable Instruments Act 1881 (Section 138), cheque dishonour is a criminal offence. The payee must: (1) receive dishonour notice from bank, (2) send legal notice to drawer within 30 days of dishonour, (3) file criminal complaint within 30 days if payment not received within 30 days of notice.",
      application: "Three strict deadlines apply — missing any one bars your legal remedy. Collect the dishonour memo from your bank immediately. Send a legal notice demanding payment within 30 days. If unpaid, file criminal complaint at Magistrate Court within the next 30 days.",
      conclusion: "⚠️ Three 30-day deadlines — do not miss any one of them.\n\n📋 **Cheque bounce case document list?** — Document List: ৳99\n📄 **Legal notice template + full procedure guide?** — Procedure Guide: ৳999\n📄 **Complete cheque bounce case pack?** — Full Pack: ৳2,999",
    },
    escalate: false,
    relatedRules: ["prop-cheque-001"],
    lastVerified: "2025-03-09",
  },

  // ── CATEGORY 11: APARTMENT/FLAT ───────────────────────────
  {
    id: "prop-qa-flat-001",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["flat possession", "builder not giving flat", "apartment not handed over", "developer default", "REHAB developer"],
    question: "I paid for a flat but the builder is not handing it over — what can I do?",
    irac: {
      issue: "Whether a flat buyer can compel a developer to hand over possession of a purchased apartment.",
      rule: "Under the Real Estate Development and Management Act 2010, developers must fulfil contractual obligations and hand over possession as agreed. A buyer can file for specific performance under the Specific Relief Act 1877. Additionally, the Real Estate Regulatory Authority (RERA) handles complaints against registered developers.",
      application: "First, review your sale agreement for the agreed handover date. If overdue, send a formal legal notice. Then file complaint with REHAB (Real Estate and Housing Association of Bangladesh) and/or file a suit for specific performance in Civil Court.",
      conclusion: "Keep all payment receipts, sale agreement, and correspondence with the developer.\n\n📋 **Flat possession dispute document list?** — Document List: ৳299\n📄 **Full procedure guide — complaint + specific performance?** — Procedure Guide: ৳2,999\n📄 **Complete flat dispute pack (highest value)?** — Full Pack: ৳9,999",
    },
    escalate: true,
    escalateReason: "High-value dispute. WhatsApp NLC for referral to property specialist advocate.",
    relatedRules: ["prop-title-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "prop-qa-flat-002",
    area: "property",
    jurisdiction: "BD",
    triggerKeywords: ["RAJUK flat", "RAJUK plot", "RAJUK allotment", "RAJUK dispute"],
    question: "I have a dispute over my RAJUK flat/plot allotment — what can I do?",
    irac: {
      issue: "How a person disputes a RAJUK flat or plot allotment decision.",
      rule: "RAJUK (Rajdhani Unnayan Kartripakkha) allotments are governed by specific RAJUK schemes and rules. Disputes over allotments can be challenged through RAJUK's internal appeal mechanism and then through the High Court Division via writ petition.",
      application: "First file a written complaint/appeal to the RAJUK Chairman. If rejected, file a writ petition in the High Court Division challenging the allotment decision as illegal or procedurally unfair.",
      conclusion: "Keep all original allotment documents, payment receipts, and correspondence with RAJUK.\n\n📋 **RAJUK dispute document list?** — Document List: ৳299\n📄 **Full RAJUK appeal procedure?** — Procedure Guide: ৳3,999\n📄 **Complete RAJUK dispute pack?** — Full Pack: ৳9,999–19,999",
    },
    escalate: true,
    escalateReason: "RAJUK disputes often require writ petition. WhatsApp NLC for referral.",
    relatedRules: [],
    lastVerified: "2025-03-09",
  },
];

const propertyModule: KnowledgeModule = {
  area: "property",
  label: "Land, Property & Money Disputes",
  description: "212 topics covering title disputes, boundary/encroachment, inheritance, mortgage, mutation, cheque bounce, flat/apartment disputes, and more — Bangladesh's most common civil matters.",
  rules,
  qaBank,
};

export default propertyModule;
